"use client";
import {FormEvent,useEffect,useState} from "react";
import {Check,Copy,KeyRound,Loader2,PlugZap,Plus,Radio,ShieldCheck} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";

type Project={id:string;name:string;domain?:string;pixelId?:string;metaConnectedAt?:string};
type Credential={id:string;name:string;provider:string;projectId:string;active:boolean;createdAt:string;lastUsedAt?:string};
const input="w-full rounded-lg border border-white/10 bg-black/25 px-3 py-2.5 text-sm outline-none focus:border-violet-400";
function CopyField({label,value,secret=false}:{label:string;value:string;secret?:boolean}){const[c,setC]=useState(false);const copy=async()=>{await navigator.clipboard.writeText(value);setC(true);setTimeout(()=>setC(false),1600)};return <div><div className="mb-1 flex justify-between text-xs text-slate-400"><span>{label}</span>{secret&&<span className="text-amber-300">Copie agora: não será exibido novamente</span>}</div><div className="flex gap-2"><code className="min-w-0 flex-1 break-all rounded-lg bg-black/35 p-3 text-xs text-sky-300">{value}</code><Button type="button" variant="outline" size="icon" onClick={copy}>{c?<Check/>:<Copy/>}</Button></div></div>}
export function PixelConnect(){const[projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(""),[pixelId,setPixelId]=useState(""),[token,setToken]=useState(""),[testCode,setTestCode]=useState(""),[businessId,setBusinessId]=useState(""),[pixelName,setPixelName]=useState("Pixel TrackBase"),[busy,setBusy]=useState(false),[creating,setCreating]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{fetch("/api/projects").then(r=>r.json()).then(b=>{setProjects(b.projects||[]);if(b.projects?.[0])setProjectId(b.projects[0].id)});},[]);
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setMessage("");try{const r=await fetch("/api/meta/connect",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId,pixelId,accessToken:token,testCode})}),b=await r.json();if(!r.ok)throw new Error(b.error||"Não foi possível conectar.");setMessage(`Pixel ${b.pixelId} conectado. O CAPI já receberá os mesmos event_id do script.`);setToken("")}catch(e){setMessage(e instanceof Error?e.message:"Erro ao conectar.")}finally{setBusy(false)}};
 const createPixel=async()=>{setCreating(true);setMessage("");try{const r=await fetch("/api/meta/pixel/create",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId,businessId,name:pixelName})}),b=await r.json();if(!r.ok)throw new Error(b.error||"Não foi possível criar o Pixel.");setPixelId(b.pixelId);setMessage(`Pixel ${b.pixelId} criado na Meta. Agora gere o token CAPI no Gerenciador de Eventos e conecte abaixo.`)}catch(e){setMessage(e instanceof Error?e.message:"Erro ao criar Pixel.")}finally{setCreating(false)}};
 return <Card className="metric-card"><CardHeader><CardTitle className="flex items-center gap-2"><Radio className="size-5 text-violet-300"/>Pixel Meta + Conversions API</CardTitle></CardHeader><CardContent><p className="mb-5 text-sm leading-6 text-slate-400">Crie um novo Pixel pela TrackBase ou conecte um existente. Depois, a TrackBase envia PageView, ViewContent, InitiateCheckout e Purchase pelo navegador e servidor com o mesmo <code>event_id</code>.</p>{projects.length===0?<p className="rounded-lg border border-amber-500/30 bg-amber-500/10 p-4 text-sm text-amber-200">Crie primeiro um projeto na aba UTMs.</p>:<><div className="mb-6 grid gap-4 rounded-xl border border-violet-400/20 bg-violet-500/[.05] p-4 md:grid-cols-3"><label className="text-sm">Projeto<select className={input+" mt-1"} value={projectId} onChange={e=>setProjectId(e.target.value)}>{projects.map(p=><option className="bg-[#101522]" key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="text-sm">Nome do novo Pixel<input className={input+" mt-1"} value={pixelName} onChange={e=>setPixelName(e.target.value)} /></label><label className="text-sm">ID do negócio Meta<input className={input+" mt-1"} value={businessId} onChange={e=>setBusinessId(e.target.value.replace(/\D/g,""))} placeholder="Business ID" /></label><div className="md:col-span-3"><Button type="button" variant="outline" disabled={creating||!businessId||!pixelName} onClick={createPixel}>{creating?<Loader2 className="animate-spin"/>:<Plus/>}Criar Pixel na Meta</Button></div></div><form onSubmit={submit} className="grid gap-4 md:grid-cols-2"><label className="text-sm">ID do Pixel<input className={input+" mt-1"} value={pixelId} onChange={e=>setPixelId(e.target.value.replace(/\D/g,""))} placeholder="Ex.: 123456789012345" required/></label><div className="hidden md:block"/><label className="text-sm md:col-span-2">Token de acesso da Conversions API<input type="password" className={input+" mt-1"} value={token} onChange={e=>setToken(e.target.value)} placeholder="Token gerado no Gerenciador de Eventos da Meta" required/></label><label className="text-sm md:col-span-2">Código de teste da Meta <span className="text-slate-500">(opcional)</span><input className={input+" mt-1"} value={testCode} onChange={e=>setTestCode(e.target.value)} placeholder="TEST12345"/></label><div className="md:col-span-2"><Button disabled={busy}>{busy?<Loader2 className="animate-spin"/>:<ShieldCheck/>}Validar e conectar Pixel + CAPI</Button></div></form></>}{message&&<p className={`mt-4 rounded-lg p-3 text-sm ${message.startsWith("Pixel")?"bg-emerald-500/10 text-emerald-200":"bg-red-500/10 text-red-200"}`}>{message}</p>}</CardContent></Card>}
export function GatewayConnect(){const[projects,setProjects]=useState<Project[]>([]),[credentials,setCredentials]=useState<Credential[]>([]),[projectId,setProjectId]=useState(""),[name,setName]=useState("FortPay produção"),[provider,setProvider]=useState("fortpay"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[created,setCreated]=useState<{token:string;webhookUrl:string;authorization:string}|null>(null);
 const load=async()=>{const[p,c]=await Promise.all([fetch("/api/projects").then(r=>r.json()),fetch("/api/credentials").then(r=>r.json())]);setProjects(p.projects||[]);setCredentials(c.credentials||[]);if(!projectId&&p.projects?.[0])setProjectId(p.projects[0].id)};useEffect(()=>{load()},[]);
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError("");setCreated(null);try{const r=await fetch("/api/credentials",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId,name,provider})}),b=await r.json();if(!r.ok)throw new Error(b.error||"Erro ao criar credencial.");setCreated(b.credential);await load()}catch(e){setError(e instanceof Error?e.message:"Erro ao criar credencial.")}finally{setBusy(false)}};
 return <Card className="metric-card"><CardHeader><CardTitle className="flex items-center gap-2"><PlugZap className="size-5 text-violet-300"/>Gateways e webhooks de venda</CardTitle></CardHeader><CardContent className="space-y-5"><p className="text-sm leading-6 text-slate-400">Crie uma credencial por gateway. Cole a URL e o token no webhook do FortPay ou de qualquer outra plataforma. Pagamentos aprovados viram <b>Purchase</b>; pendentes, reembolso e chargeback também entram no painel.</p>{projects.length===0?<p className="rounded-lg border border-amber-500/30 bg-amber-500/10 p-4 text-sm text-amber-200">Crie primeiro um projeto na aba UTMs.</p>:<form onSubmit={submit} className="grid gap-4 md:grid-cols-3"><label className="text-sm">Projeto<select className={input+" mt-1"} value={projectId} onChange={e=>setProjectId(e.target.value)}>{projects.map(p=><option className="bg-[#101522]" key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="text-sm">Gateway<select className={input+" mt-1"} value={provider} onChange={e=>setProvider(e.target.value)}>{[["fortpay","FortPay"],["flevopay","FlevoPay"],["hotmart","Hotmart"],["kiwify","Kiwify"],["generic","Outro gateway"]].map(([v,l])=><option className="bg-[#101522]" key={v} value={v}>{l}</option>)}</select></label><label className="text-sm">Nome da credencial<input className={input+" mt-1"} value={name} onChange={e=>setName(e.target.value)} required/></label><div className="md:col-span-3"><Button disabled={busy}>{busy?<Loader2 className="animate-spin"/>:<KeyRound/>}Criar credencial de API</Button></div></form>}{created&&<div className="space-y-3 rounded-xl border border-emerald-400/25 bg-emerald-500/[.06] p-4"><b className="text-emerald-200">Credencial criada para o gateway</b><CopyField label="URL do webhook" value={created.webhookUrl}/><CopyField label="Token / Authorization Bearer" value={created.token} secret/></div>}{error&&<p className="rounded-lg bg-red-500/10 p-3 text-sm text-red-200">{error}</p>}<div className="border-t border-white/10 pt-4"><h4 className="mb-3 text-sm font-medium">Credenciais ativas</h4>{credentials.length?<div className="space-y-2">{credentials.map(c=><div className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-white/8 p-3 text-sm" key={c.id}><span><b>{c.name}</b> <span className="text-slate-500">· {c.provider}</span></span><span className="text-xs text-slate-500">{c.lastUsedAt?`Último evento: ${new Date(c.lastUsedAt).toLocaleString("pt-BR")}`:"Sem eventos ainda"}</span></div>)}</div>:<p className="text-sm text-slate-500">Nenhuma credencial criada.</p>}</div></CardContent></Card>}
