"use client";
import { useEffect, useState } from "react";
import { ArrowLeft, CheckCircle2, Copy, KeyRound, LockKeyhole, Plus, Radio, Webhook } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { MetaAccountsClient } from "../contas-meta/accounts-client";

type Project={id:string;name:string;domain:string|null;publicKey:string;pixelId:string|null;metaConnectedAt:string|null};
type NewCredential={token:string;webhookUrl:string;authorization:string;name:string};
function GatewayCredentialCard({projects,selected,setSelected,onCreate,credential}:{projects:Project[];selected:string;setSelected:(id:string)=>void;onCreate:(e:React.FormEvent<HTMLFormElement>)=>void;credential:NewCredential|null}){
 return <Card className="metric-card mt-5"><CardHeader><CardTitle className="flex items-center gap-2"><Webhook className="size-5 text-fuchsia-400"/>Criar credencial de API para gateway</CardTitle></CardHeader><CardContent><form onSubmit={onCreate} className="grid gap-4 md:grid-cols-3"><div><Label>Projeto</Label><Select value={selected} onValueChange={setSelected}><SelectTrigger className="mt-2 w-full"><SelectValue placeholder="Selecione"/></SelectTrigger><SelectContent>{projects.map(p=><SelectItem value={p.id} key={p.id}>{p.name}</SelectItem>)}</SelectContent></Select></div><div><Label>Gateway</Label><Select name="provider" defaultValue="fortpay"><SelectTrigger className="mt-2 w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="fortpay">FortPay</SelectItem><SelectItem value="generic">Outro gateway</SelectItem></SelectContent></Select></div><div><Label>Nome da credencial</Label><Input name="credentialName" required defaultValue="FortPay Principal" className="mt-2"/></div><Button disabled={!selected} className="md:col-span-3">Criar credencial de API</Button></form>{credential&&<div className="mt-5 space-y-4 rounded-xl border border-fuchsia-500/20 bg-fuchsia-500/[.06] p-4"><p className="font-medium">Copie estes dados para a FortPay</p><CopyField label="URL do webhook" value={credential.webhookUrl}/><CopyField label="Credencial / Token da API" value={credential.token}/><p className="text-sm text-slate-400">Se a FortPay pedir um cabeçalho, use <code>Authorization: Bearer SUA_CREDENCIAL</code>. Se pedir somente a credencial, cole apenas o token.</p></div>}</CardContent></Card>
}
function CopyField({label,value}:{label:string;value:string}){return <div><Label>{label}</Label><div className="mt-2 flex gap-2"><code className="min-w-0 flex-1 overflow-x-auto rounded-lg bg-black/30 p-3 text-sm text-sky-300">{value}</code><Button type="button" variant="outline" size="icon" onClick={()=>navigator.clipboard.writeText(value)}><Copy className="size-4"/></Button></div></div>}
export default function IntegrationSetup(){
 const [projects,setProjects]=useState<Project[]>([]),[selected,setSelected]=useState(""),[message,setMessage]=useState(""),[script,setScript]=useState(""),[secret,setSecret]=useState("");
 const [apiCredential,setApiCredential]=useState<NewCredential|null>(null);
 const load=()=>fetch("/api/projects").then(r=>r.json()).then(d=>{setProjects(d.projects||[]);if(!selected&&d.projects?.[0])setSelected(d.projects[0].id)});
 useEffect(()=>{load()},[]);
 async function createProject(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setMessage("Criando projeto...");const f=new FormData(e.currentTarget);const r=await fetch("/api/projects",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:f.get("name"),domain:f.get("domain")})});const d=await r.json();if(!r.ok)return setMessage(d.error||"Erro ao criar");setScript(d.script);setSecret(d.webhookSecret);setMessage("Projeto criado. Guarde o segredo do webhook.");await load();setSelected(d.project.id)}
 async function connect(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setMessage("Validando com a Meta...");const f=new FormData(e.currentTarget);const r=await fetch("/api/meta/connect",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId:selected,pixelId:f.get("pixelId"),accessToken:f.get("accessToken"),testCode:f.get("testCode")})});const d=await r.json();setMessage(r.ok?"Pixel e CAPI conectados com sucesso.":d.error||"Não foi possível conectar");if(r.ok)load()}
 async function createCredential(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setMessage("Criando credencial...");const f=new FormData(e.currentTarget);const r=await fetch("/api/credentials",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({projectId:selected,name:f.get("credentialName"),provider:f.get("provider")})});const d=await r.json();if(!r.ok)return setMessage(d.error||"Não foi possível criar");setApiCredential(d.credential);setMessage("Credencial criada. Copie agora: a chave não será exibida novamente.")}
 const current=projects.find(p=>p.id===selected);
 const installScript=script||`<script async src="https://meta-track-br.kitbiblico0.chatgpt.site/tracker.js?key=${current?.publicKey||""}"></script>`;
 return <main className="min-h-screen bg-[#080b12] px-5 py-8 text-slate-100 lg:px-10"><div className="mx-auto max-w-6xl">
  <a href="/" className="mb-7 inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ArrowLeft className="size-4"/>Voltar ao painel</a>
  <div className="mb-7 flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl bg-violet-600"><Radio/></div><div><h1 className="text-2xl font-semibold">TrackBase Analytics</h1><p className="text-slate-500">Pixel, CAPI e rastreamento</p></div></div>
  <div className="mb-5 flex gap-3 rounded-xl border border-emerald-400/20 bg-emerald-400/[.06] p-4 text-sm text-emerald-100"><CheckCircle2 className="mt-0.5 size-5 shrink-0"/><div><b>Coletor externo preparado</b><p className="mt-1 text-emerald-200/70">PageView, IC e webhooks entram pelos endpoints públicos. O painel e as credenciais exigem login.</p></div></div>
  {message&&<div className="mb-5 rounded-xl border border-violet-500/20 bg-violet-500/10 p-3 text-sm text-violet-200">{message}</div>}
  <Card className="metric-card mb-5"><CardHeader><CardTitle>Contas do Gerenciador de Anúncios</CardTitle></CardHeader><CardContent><p className="mb-5 text-sm text-slate-400">Conecte quantos logins Meta precisar. As contas já conectadas continuam salvas quando você autorizar outro perfil.</p><MetaAccountsClient/></CardContent></Card>
  <div className="grid gap-5 lg:grid-cols-2">
   <Card className="metric-card"><CardHeader><CardTitle className="flex items-center gap-2"><Plus className="size-5 text-violet-400"/>1. Criar projeto</CardTitle></CardHeader><CardContent><form onSubmit={createProject} className="space-y-4"><div><Label>Nome da oferta ou loja</Label><Input name="name" required placeholder="Ex.: JetHose LATAM" className="mt-2"/></div><div><Label>Domínio da página</Label><Input name="domain" placeholder="https://minhaoferta.com" className="mt-2"/></div><Button className="w-full">Criar projeto e gerar script</Button></form></CardContent></Card>
   <Card className="metric-card"><CardHeader><CardTitle className="flex items-center gap-2"><KeyRound className="size-5 text-sky-400"/>2. Conectar Meta</CardTitle></CardHeader><CardContent><form onSubmit={connect} className="space-y-4"><div><Label>Projeto</Label><Select value={selected} onValueChange={setSelected}><SelectTrigger className="mt-2 w-full"><SelectValue placeholder="Crie um projeto primeiro"/></SelectTrigger><SelectContent>{projects.map(p=><SelectItem value={p.id} key={p.id}>{p.name}</SelectItem>)}</SelectContent></Select></div><div><Label>Pixel ID</Label><Input name="pixelId" required inputMode="numeric" placeholder="000000000000000" className="mt-2"/></div><div><Label>Token da API de Conversões</Label><Input name="accessToken" required type="password" placeholder="Cole o token gerado na Meta" className="mt-2"/></div><div><Label>Código de evento de teste (opcional)</Label><Input name="testCode" placeholder="TEST12345" className="mt-2"/></div><Button disabled={!selected} className="w-full">Validar e conectar</Button>{current?.metaConnectedAt&&<p className="flex items-center gap-2 text-sm text-emerald-400"><CheckCircle2 className="size-4"/>Pixel {current.pixelId} conectado</p>}</form></CardContent></Card>
  </div>
  {(script||current)&&<Card className="metric-card mt-5"><CardHeader><CardTitle className="flex items-center gap-2"><LockKeyhole className="size-5 text-emerald-400"/>3. Instalação</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-slate-400">Cole antes de <code>&lt;/head&gt;</code> em todas as páginas da oferta.</p><div className="flex gap-2"><code className="min-w-0 flex-1 overflow-x-auto rounded-lg bg-black/30 p-4 text-sm text-sky-300">{installScript}</code><Button variant="outline" size="icon" onClick={()=>navigator.clipboard.writeText(installScript)}><Copy className="size-4"/></Button></div>{secret&&<div><Label>Segredo do webhook — mostrado uma única vez</Label><code className="mt-2 block overflow-x-auto rounded-lg bg-black/30 p-4 text-sm text-amber-300">{secret}</code></div>}<p className="text-sm text-slate-500">Eventos automáticos: PageView, ViewContent e clique de checkout. Eventos manuais: <code>{'TrackBase.track("Purchase", { value: 99.90, currency: "BRL" })'}</code>.</p></CardContent></Card>}
  <GatewayCredentialCard projects={projects} selected={selected} setSelected={setSelected} onCreate={createCredential} credential={apiCredential}/>
 </div></main>
}
