"use client";
import {useState} from "react";
import {ArrowLeft,Check,Copy,FileText,Megaphone,Radio,PlugZap} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Tabs,TabsContent,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {MetaAccountsClient} from "../contas-meta/accounts-client";
import {TrackingInstall} from "./tracking-install";
import {GatewayConnect,PixelConnect} from "./connections";

const metaUtm="utm_source=facebook&utm_medium=paid&utm_campaign={{campaign.name}}|{{campaign.id}}&utm_content={{ad.name}}|{{ad.id}}&utm_term={{adset.name}}|{{adset.id}}&placement={{placement}}&site_source_name={{site_source_name}}";

export default function IntegrationSetup(){const[copied,setCopied]=useState(false);async function copyUtm(){await navigator.clipboard.writeText(metaUtm);setCopied(true);setTimeout(()=>setCopied(false),1800)}return <main className="min-h-screen bg-slate-50 px-4 py-6 text-slate-900 sm:px-6 lg:px-10"><div className="mx-auto max-w-[1500px]">
<div className="mb-6 flex flex-wrap items-center justify-between gap-3"><a href="/" className="inline-flex items-center gap-2 text-sm text-slate-600 transition hover:text-white"><ArrowLeft className="size-4"/>Voltar ao dashboard</a><span className="rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1.5 text-xs text-emerald-300">Ambiente conectado</span></div>
<div className="mb-8 flex items-center gap-4 rounded-2xl border border-slate-200 bg-slate-50 p-5"><img src="/trackbase-logo.png" alt="Logo TrackBase Analytics" className="h-12 w-24 shrink-0 object-contain"/><div><div><p className="text-xs font-medium uppercase tracking-[.18em] text-blue-600/80">Configuração</p><h1 className="mt-1 text-2xl font-semibold">Integrações</h1><p className="mt-1 text-sm text-slate-500">Conecte anúncios, rastreamento, Pixel e gateways de vendas.</p></div></div></div>
<Tabs defaultValue="ads" className="w-full"><TabsList className="mb-5 grid h-auto w-full grid-cols-2 rounded-xl border border-slate-200 bg-white p-1 sm:h-14 sm:grid-cols-4"><TabsTrigger value="ads" className="h-11 gap-2 text-sm sm:h-full"><Megaphone className="size-4"/>Anúncios</TabsTrigger><TabsTrigger value="utms" className="h-11 gap-2 text-sm sm:h-full"><FileText className="size-4"/>UTMs</TabsTrigger><TabsTrigger value="pixel" className="h-11 gap-2 text-sm sm:h-full"><Radio className="size-4"/>Pixel & CAPI</TabsTrigger><TabsTrigger value="gateways" className="h-11 gap-2 text-sm sm:h-full"><PlugZap className="size-4"/>Gateways</TabsTrigger></TabsList>
<TabsContent value="ads"><Card className="metric-card"><CardHeader><CardTitle>Contas do Gerenciador de Anúncios</CardTitle></CardHeader><CardContent><p className="mb-5 text-sm leading-6 text-slate-600">Entre com a Meta, escolha a conta que será vinculada e use “Conectar outra conta Meta” para adicionar outros logins.</p><MetaAccountsClient/></CardContent></Card></TabsContent>
<TabsContent value="utms"><Card className="metric-card"><CardHeader><CardTitle>UTMs e script da página</CardTitle></CardHeader><CardContent className="space-y-5"><p className="text-sm leading-6 text-slate-600">Copie e cole no campo <b className="text-slate-200">Parâmetros de URL</b> do anúncio. A Meta preencherá campanha, conjunto, anúncio e posicionamento automaticamente.</p><div className="rounded-xl border border-violet-500/20 bg-slate-50 p-4"><code className="block break-all text-sm leading-7 text-blue-600">{metaUtm}</code></div><Button onClick={copyUtm} className="min-w-44">{copied?<><Check/>Copiado</>:<><Copy/>Copiar UTMs</>}</Button><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[["utm_campaign","Campanha + ID"],["utm_term","Conjunto + ID"],["utm_content","Anúncio + ID"],["placement","Posicionamento"],["site_source_name","Facebook ou Instagram"],["utm_medium","Tráfego pago"]].map(([key,value])=><div key={key} className="rounded-lg border border-slate-200 bg-slate-50 p-3"><code className="text-xs text-blue-600">{key}</code><p className="mt-1 text-sm text-slate-300">{value}</p></div>)}</div><TrackingInstall/></CardContent></Card></TabsContent>
<TabsContent value="pixel"><PixelConnect/></TabsContent><TabsContent value="gateways"><GatewayConnect/></TabsContent>
</Tabs></div></main>}
