"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {ArrowLeft,Check,Copy,FileText,Megaphone,Radio,PlugZap,ShieldCheck} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Tabs,TabsContent,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {MetaAccountsClient} from "../contas-meta/accounts-client";
import {TrackingInstall} from "./tracking-install";
import {MobileMenu} from "@/components/MobileMenu";
import {GatewayConnect,PixelConnect} from "./connections";
import { copyText } from "@/lib/clipboard";

const metaUtm="utm_source=facebook&utm_medium=paid&utm_campaign={{campaign.name}}|{{campaign.id}}&utm_content={{ad.name}}|{{ad.id}}&utm_term={{adset.name}}|{{adset.id}}&placement={{placement}}&site_source_name={{site_source_name}}";

export default function IntegrationSetup(){const[copied,setCopied]=useState(false);const[tab,setTab]=useState("ads");useEffect(()=>{try{const h=window.location.hash.replace("#","");if(["ads","utms","pixel","gateways"].includes(h))setTab(h)}catch{}},[]);function changeTab(value:string){setTab(value);try{history.replaceState(null,"",`${location.pathname}${location.search}#${value}`)}catch{}}async function copyUtm(){if(await copyText(metaUtm)){setCopied(true);setTimeout(()=>setCopied(false),1800)}}return <main className="min-h-screen overflow-x-hidden bg-slate-50 px-3 pb-10 pt-[max(1rem,env(safe-area-inset-top))] text-slate-900 sm:px-6 sm:py-7 lg:px-10"><div className="mx-auto w-full max-w-7xl">
<div className="mb-4 lg:hidden"><MobileMenu/></div>
<div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><Link href="/" className="inline-flex min-h-11 items-center gap-2 self-start rounded-lg px-1 text-sm font-medium text-slate-600 transition hover:text-blue-600"><ArrowLeft className="size-4"/>Voltar ao dashboard</Link><div className="grid grid-cols-1 gap-2 min-[390px]:grid-cols-[1fr_auto] sm:flex sm:items-center"><Link href="/docs" className="inline-flex min-h-11 min-w-0 items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-3 text-sm font-medium text-slate-600 transition hover:border-blue-300 hover:text-blue-600"><FileText className="size-4 shrink-0"/><span className="truncate">Documentação</span></Link><span className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border border-emerald-400/25 bg-emerald-400/10 px-3 text-sm font-medium text-emerald-700"><ShieldCheck className="size-4 shrink-0"/>Ambiente conectado</span></div></div>
<section className="relative mb-6 overflow-hidden rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div aria-hidden className="absolute -right-16 -top-20 size-48 rounded-full bg-blue-500/10 blur-3xl"/><div className="relative flex flex-col gap-5 sm:flex-row sm:items-center"><div className="flex h-14 w-fit max-w-[190px] items-center rounded-xl bg-slate-50 px-3 sm:h-16 sm:max-w-[220px]"><img src="/ghostscale-logo.png" alt="GhostScale" className="h-auto max-h-11 w-full object-contain sm:max-h-12"/></div><div className="min-w-0"><p className="text-[11px] font-semibold uppercase tracking-[.18em] text-blue-600">Central de configuração</p><h1 className="mt-1 text-2xl font-bold tracking-tight sm:text-3xl">Integrações</h1><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-500 sm:text-base">Conecte anúncios, rastreamento, Pixel e gateways de vendas em um só lugar.</p></div></div></section>
<Tabs value={tab} onValueChange={changeTab} className="w-full"><TabsList aria-label="Tipos de integração" className="mb-6 !grid !h-auto w-full grid-cols-2 gap-1 rounded-xl border border-slate-200 bg-white p-1.5 shadow-sm sm:grid-cols-4"><TabsTrigger value="ads" className="!h-12 min-w-0 gap-1.5 rounded-lg px-2 text-xs sm:gap-2 sm:text-sm"><Megaphone className="size-4 shrink-0"/><span className="truncate">Anúncios</span></TabsTrigger><TabsTrigger value="utms" className="!h-12 min-w-0 gap-1.5 rounded-lg px-2 text-xs sm:gap-2 sm:text-sm"><FileText className="size-4 shrink-0"/><span className="truncate">UTMs</span></TabsTrigger><TabsTrigger value="pixel" className="!h-12 min-w-0 gap-1.5 rounded-lg px-2 text-xs sm:gap-2 sm:text-sm"><Radio className="size-4 shrink-0"/><span className="truncate">Pixel & CAPI</span></TabsTrigger><TabsTrigger value="gateways" className="!h-12 min-w-0 gap-1.5 rounded-lg px-2 text-xs sm:gap-2 sm:text-sm"><PlugZap className="size-4 shrink-0"/><span className="truncate">Gateways</span></TabsTrigger></TabsList>
<TabsContent value="ads"><Card className="metric-card overflow-hidden"><CardHeader className="border-b border-slate-200 px-4 py-5 sm:px-6"><CardTitle className="text-lg leading-tight sm:text-xl">Contas do Gerenciador de Anúncios</CardTitle><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Entre com a Meta, escolha uma conta e vincule-a ao seu projeto. Você também pode adicionar outros logins.</p></CardHeader><CardContent className="px-4 py-5 sm:px-6"><MetaAccountsClient/></CardContent></Card></TabsContent>
<TabsContent value="utms"><Card className="metric-card"><CardHeader><CardTitle>UTMs e script da página</CardTitle></CardHeader><CardContent className="space-y-5"><p className="text-sm leading-6 text-slate-600">Copie e cole no campo <b className="text-slate-700">Parâmetros de URL</b> do anúncio. A Meta preencherá campanha, conjunto, anúncio e posicionamento automaticamente.</p><div className="rounded-xl border border-violet-500/20 bg-slate-50 p-4"><code className="block break-all text-sm leading-7 text-blue-600">{metaUtm}</code></div><Button onClick={copyUtm} className="min-w-44">{copied?<><Check/>Copiado</>:<><Copy/>Copiar UTMs</>}</Button><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[["utm_campaign","Campanha + ID"],["utm_term","Conjunto + ID"],["utm_content","Anúncio + ID"],["placement","Posicionamento"],["site_source_name","Facebook ou Instagram"],["utm_medium","Tráfego pago"]].map(([key,value])=><div key={key} className="rounded-lg border border-slate-200 bg-slate-50 p-3"><code className="text-xs text-blue-600">{key}</code><p className="mt-1 text-sm text-slate-500">{value}</p></div>)}</div><TrackingInstall/></CardContent></Card></TabsContent>
<TabsContent value="pixel"><PixelConnect/></TabsContent><TabsContent value="gateways"><GatewayConnect/></TabsContent>
</Tabs></div></main>}
