"use client";
import {useEffect,useState} from "react";
import {CheckCircle2,Loader2,Save,Send,Settings2} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Switch} from "@/components/ui/switch";
import type {Detection,EventRule,TrackingConfig} from "@/lib/tracking-config";
import {defaultTrackingConfig} from "@/lib/tracking-config";

const input="dashboard-input mt-1";
const labels:{key:"lead"|"addToCart"|"initiateCheckout";title:string;event:string;hint:string}[]=[
  {key:"lead",title:"Regra de Lead",event:"Lead",hint:"Ex.: ENVIAR, QUERO SABER MAIS"},
  {key:"addToCart",title:"Regra de Add To Cart",event:"AddToCart",hint:"Ex.: ADICIONAR AO CARRINHO"},
  {key:"initiateCheckout",title:"Regra de Initiate Checkout",event:"InitiateCheckout",hint:"Ex.: COMPRAR AGORA"}
];
function EventEditor({title,event,hint,value,onChange}:{title:string;event:string;hint:string;value:EventRule;onChange:(rule:EventRule)=>void}){
  return <section className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="flex items-center justify-between gap-4"><div><h4 className="font-semibold">{title}</h4><p className="mt-1 text-xs text-slate-500">Envia o evento {event} para GhostScale, Pixel e CAPI.</p></div><Switch checked={value.enabled} onCheckedChange={enabled=>onChange({...value,enabled})} aria-label={`Ativar ${title}`}/></div>{value.enabled&&<div className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-sm">Regra de detecção<select className={input} value={value.detection} onChange={e=>onChange({...value,detection:e.target.value as Detection})}><option value="text">Texto do botão contém</option><option value="selector">Seletor CSS</option><option value="url">Link contém</option></select></label><label className="text-sm">{value.detection==="selector"?"Seletor do botão":value.detection==="url"?"Trecho do link":"Texto do botão"}<input className={input} value={value.match} onChange={e=>onChange({...value,match:e.target.value})} placeholder={hint}/></label></div>}</section>
}

export function TrackingRules({projectId,enabled}:{projectId:string;enabled:boolean}){
  const[config,setConfig]=useState<TrackingConfig>(defaultTrackingConfig),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
  useEffect(()=>{if(!projectId||!enabled)return;let live=true;setLoading(true);setMessage("");fetch(`/api/projects/tracking-config?projectId=${encodeURIComponent(projectId)}`,{cache:"no-store"}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);if(live)setConfig(b.config)}).catch(e=>live&&setMessage(e instanceof Error?e.message:"Erro ao carregar regras.")).finally(()=>live&&setLoading(false));return()=>{live=false}},[projectId,enabled]);
  const save=async()=>{setSaving(true);setMessage("");try{const r=await fetch(`/api/projects/tracking-config?projectId=${encodeURIComponent(projectId)}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({config})}),b=await r.json();if(!r.ok)throw new Error(b.error||"Não foi possível salvar.");setConfig(b.config);setMessage("Regras salvas. O script instalado já passa a usar esta configuração.")}catch(e){setMessage(e instanceof Error?e.message:"Não foi possível salvar.")}finally{setSaving(false)}};
  if(!enabled)return <div className="mt-6 rounded-xl border border-dashed border-slate-200 p-5 text-sm text-slate-500">Conecte ou crie um Pixel para liberar as regras de envio.</div>;
  if(loading)return <div className="mt-6 flex items-center gap-2 text-sm text-slate-400"><Loader2 className="animate-spin"/>Carregando regras do projeto...</div>;
  return <div className="mt-7 space-y-4 border-t border-slate-200 pt-6"><div><h3 className="flex items-center gap-2 text-lg font-semibold"><Settings2 className="size-5 text-blue-600"/>Regras do Pixel e do rastreamento</h3><p className="mt-1 text-sm leading-6 text-slate-500">Escolha como cada evento é detectado. O mesmo identificador é usado no navegador e no servidor para deduplicar.</p></div>{labels.map(item=><EventEditor key={item.key} title={item.title} event={item.event} hint={item.hint} value={config[item.key]} onChange={rule=>setConfig({...config,[item.key]:rule})}/>)}
    <section className="rounded-xl border border-slate-200 bg-slate-50 p-4"><h4 className="font-semibold">Regra de Purchase</h4><div className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-sm">Configuração de envio<select className={input} value={config.purchase.mode} onChange={e=>setConfig({...config,purchase:{...config.purchase,mode:e.target.value as TrackingConfig["purchase"]["mode"]}})}><option value="gateway_approved">Apenas vendas aprovadas pelo gateway</option><option value="thank_you">Página de obrigado</option></select></label><label className="text-sm">Valor do envio<select className={input} value={config.purchase.valueSource} onChange={e=>setConfig({...config,purchase:{...config.purchase,valueSource:e.target.value as "sale"|"fixed"}})}><option value="sale">Valor da venda</option><option value="fixed">Valor fixo</option></select></label>{config.purchase.valueSource==="fixed"&&<label className="text-sm">Valor fixo (R$)<input type="number" min="0" step="0.01" className={input} value={config.purchase.fixedValue} onChange={e=>setConfig({...config,purchase:{...config.purchase,fixedValue:Number(e.target.value)}})}/></label>}<label className="text-sm">Produto<input className={input} value={config.purchase.product} onChange={e=>setConfig({...config,purchase:{...config.purchase,product:e.target.value}})} placeholder="any"/></label>{config.purchase.mode==="thank_you"&&<label className="text-sm md:col-span-2">URL da página de obrigado contém<input className={input} value={config.purchase.thankYouMatch} onChange={e=>setConfig({...config,purchase:{...config.purchase,thankYouMatch:e.target.value}})} placeholder="/obrigado"/></label>}</div></section>
    <section className="rounded-xl border border-sky-400/15 bg-sky-500/[.04] p-4"><h4 className="flex items-center gap-2 font-semibold"><Send className="size-4 text-blue-600"/>Dados enviados ao checkout e ao gateway</h4><p className="mt-1 text-xs leading-5 text-slate-500">O script adiciona os dados aos links e como campos ocultos nos formulários. O gateway deve devolvê-los no webhook.</p><div className="mt-4 grid gap-3 md:grid-cols-3">{[["forwardUtms","UTMs","utm_source, campaign, content e term"],["forwardFacebook","Dados Meta","fbclid, fbc e fbp"],["forwardVisitor","Visitante GhostScale","tb_vid para unir clique e compra"]].map(([key,title,hint])=><label key={key} className="flex items-start justify-between gap-3 rounded-lg border border-slate-200 p-3"><span><b className="text-sm">{title}</b><span className="mt-1 block text-xs text-slate-500">{hint}</span></span><Switch checked={config.gateway[key as keyof TrackingConfig["gateway"]]} onCheckedChange={checked=>setConfig({...config,gateway:{...config.gateway,[key]:checked}})} aria-label={`Enviar ${title}`}/></label>)}</div></section>
    <section className="rounded-xl border border-slate-200 bg-slate-50 p-4"><h4 className="font-semibold">Envio de IP nos eventos</h4><label className="mt-3 block text-sm">Configuração do endereço IP<select className={input} value={config.ipMode} onChange={e=>setConfig({...config,ipMode:e.target.value as TrackingConfig["ipMode"]})}><option value="auto">Enviar IPv6 se houver; usar IPv4 como alternativa</option><option value="ipv4">Enviar somente IPv4 quando disponível</option><option value="disabled">Não enviar endereço IP</option></select></label></section>
    <Button type="button" onClick={save} disabled={saving}>{saving?<Loader2 className="animate-spin"/>:<Save/>}Salvar regras</Button>{message&&<p className={`flex items-center gap-2 rounded-lg p-3 text-sm ${message.startsWith("Regras salvas")?"bg-emerald-50 text-emerald-700":"bg-red-50 text-red-600"}`}>{message.startsWith("Regras salvas")&&<CheckCircle2 className="size-4"/>}{message}</p>}
  </div>;
}
