import {eq} from "drizzle-orm";
import {ensureDb,getDb} from "@/db";
import {projects} from "@/db/schema";
import {parseTrackingConfig} from "@/lib/tracking-config";
export async function GET(request:Request){
  const key=new URL(request.url).searchParams.get("key")||"",endpoint=new URL("/api/events",request.url).toString();let pixelId="",config=parseTrackingConfig(null);try{if(key){await ensureDb();const[project]=await getDb().select({pixelId:projects.pixelId,trackingConfig:projects.trackingConfig}).from(projects).where(eq(projects.publicKey,key)).limit(1);pixelId=project?.pixelId||"";config=parseTrackingConfig(project?.trackingConfig)}}catch(error){console.error("Tracker pixel lookup",error)}
  const script=`(()=>{const K=${JSON.stringify(key)},E=${JSON.stringify(endpoint)},P=${JSON.stringify(pixelId)},C=${JSON.stringify(config)},A="tb_attribution",TTL=7776000000,U=["utm_source","utm_medium","utm_campaign","utm_content","utm_term","fbclid","placement","site_source_name"];
const id=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random().toString(16).slice(2),cookie=n=>document.cookie.split("; ").find(x=>x.startsWith(n+"="))?.split("=").slice(1).join("=")||"",q=()=>new URLSearchParams(location.search);
let attribution={};try{attribution=JSON.parse(localStorage.getItem(A)||"{}");if(!attribution.savedAt||Date.now()-attribution.savedAt>TTL)attribution={}}catch{}const current=q(),hasCampaign=U.some(k=>current.get(k));U.forEach(k=>{const v=current.get(k);if(v)attribution[k]=v});if(hasCampaign){attribution.savedAt=Date.now();try{localStorage.setItem(A,JSON.stringify(attribution))}catch{}}
const vid=cookie("tb_vid")||id();if(!cookie("tb_vid"))document.cookie="tb_vid="+vid+";path=/;max-age=31536000;SameSite=Lax";const fbp=cookie("_fbp"),fbclid=attribution.fbclid||"",fbc=cookie("_fbc")||(fbclid?"fb.1."+Date.now()+"."+fbclid:"");let lastPage="";
if(P&&window.__tbPixelId!==P){if(!window.fbq){const f=window.fbq=function(){f.callMethod?f.callMethod.apply(f,arguments):f.queue.push(arguments)};f.push=f;f.loaded=true;f.version="2.0";f.queue=[];window._fbq=f;const s=document.createElement("script");s.async=true;s.src="https://connect.facebook.net/en_US/fbevents.js";(document.head||document.documentElement).appendChild(s)}window.fbq("init",P);window.__tbPixelId=P}
function send(eventName,data={}){const eventId=data.eventId||id(),payload={projectKey:K,eventName,eventId,eventTime:Math.floor(Date.now()/1000),url:location.href,referrer:document.referrer,visitorId:vid,fbclid,fbc,fbp,attribution,...data};const raw=JSON.stringify(payload);if(navigator.sendBeacon)navigator.sendBeacon(E,new Blob([raw],{type:"application/json"}));else fetch(E,{method:"POST",headers:{"content-type":"application/json"},body:raw,keepalive:true});if(window.fbq&&!/^(AdClick|PageError)$/.test(eventName))window.fbq("track",eventName,data,{eventID:eventId});return eventId}
function page(){const clean=location.pathname+location.search;if(clean===lastPage)return;lastPage=clean;send("PageView");send("ViewContent",{contentName:document.title})}
function forwarded(){const values={};if(C.gateway.forwardUtms)U.forEach(k=>{if(attribution[k])values[k]=attribution[k]});if(C.gateway.forwardVisitor)values.tb_vid=vid;if(C.gateway.forwardFacebook){if(fbp)values.fbp=fbp;if(fbc)values.fbc=fbc;if(fbclid)values.fbclid=fbclid}return values}
function formFields(form){Object.entries(forwarded()).forEach(([name,value])=>{let field=Array.from(form.elements||[]).find(item=>item.name===name);if(!field){field=document.createElement("input");field.type="hidden";field.name=name;form.appendChild(field)}field.value=value})}
function decorate(element){if(element.tagName==="FORM")formFields(element);const href=element.href||element.action;if(!href)return;try{const target=new URL(href,location.href);if(target.origin===location.origin&&!/checkout|pay|pagamento|comprar/i.test(target.pathname)&&element.tagName!=="FORM")return;Object.entries(forwarded()).forEach(([name,value])=>{if(!target.searchParams.has(name))target.searchParams.set(name,value)});if(element.href)element.href=target.toString();else element.action=target.toString()}catch{}}
function scan(){document.querySelectorAll("a[href],form").forEach(decorate)}
function matches(rule,target){if(!rule.enabled||!rule.match)return false;try{if(rule.detection==="selector")return target.matches(rule.match)||Boolean(target.closest(rule.match));if(rule.detection==="url")return String(target.href||target.closest("a")?.href||"").toLocaleLowerCase().includes(rule.match.toLocaleLowerCase());return String((target.textContent||"")+" "+(target.value||"")).toLocaleLowerCase().includes(rule.match.toLocaleLowerCase())}catch{return false}}
window.TrackBase={track:send,pageView:page,viewContent:data=>send("ViewContent",data),lead:data=>send("Lead",data),initiateCheckout:data=>send("InitiateCheckout",data),purchase:data=>send("Purchase",{...data,eventId:data?.eventId||(data?.externalId?"purchase_"+data.externalId:undefined)}),attribution:()=>({...attribution}),decorateLinks:scan};if(hasCampaign)send("AdClick");page();
addEventListener("error",event=>send("PageError",{message:String(event.message||"Erro de carregamento").slice(0,160)}));addEventListener("unhandledrejection",()=>send("PageError",{message:"Erro de execução"}));document.addEventListener("DOMContentLoaded",scan);new MutationObserver(scan).observe(document.documentElement,{childList:true,subtree:true});
document.addEventListener("submit",event=>{if(event.target?.tagName==="FORM")formFields(event.target)},true);
document.addEventListener("click",event=>{const target=event.target?.closest?.("a,button,input,[data-trackbase-event]");if(!target)return;decorate(target);let name=target.dataset.trackbaseEvent||"";if(!name&&matches(C.lead,target))name="Lead";else if(!name&&matches(C.addToCart,target))name="AddToCart";else if(!name&&matches(C.initiateCheckout,target))name="InitiateCheckout";if(name)send(name,{value:Number(target.dataset.value||0),currency:target.dataset.currency||"BRL",contentName:target.dataset.product||undefined})},true);
if(C.purchase.mode==="thank_you"&&C.purchase.thankYouMatch&&location.href.toLocaleLowerCase().includes(C.purchase.thankYouMatch.toLocaleLowerCase())){const purchaseKey="tb_purchase_"+location.pathname+location.search;if(!sessionStorage.getItem(purchaseKey)){sessionStorage.setItem(purchaseKey,"1");const queryValue=Number(current.get("value")||current.get("amount")||0),value=C.purchase.valueSource==="fixed"?C.purchase.fixedValue:queryValue;send("Purchase",{value,currency:current.get("currency")||"BRL",contentName:C.purchase.product==="any"?undefined:C.purchase.product,externalId:current.get("order_id")||current.get("transaction_id")||undefined})}}
const push=history.pushState,replace=history.replaceState;history.pushState=function(){push.apply(this,arguments);queueMicrotask(page)};history.replaceState=function(){replace.apply(this,arguments);queueMicrotask(page)};addEventListener("popstate",page)})();`;
  return new Response(script,{headers:{"content-type":"application/javascript; charset=utf-8","cache-control":"public, max-age=300","access-control-allow-origin":"*"}})
}
