export async function GET(request:Request){
  const key=new URL(request.url).searchParams.get("key")||"",endpoint=new URL("/api/events",request.url).toString();
  const script=`(()=>{const K=${JSON.stringify(key)},E=${JSON.stringify(endpoint)},A="tb_attribution",TTL=7776000000,U=["utm_source","utm_medium","utm_campaign","utm_content","utm_term","fbclid","placement","site_source_name"];
const id=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random().toString(16).slice(2),cookie=n=>document.cookie.split("; ").find(x=>x.startsWith(n+"="))?.split("=").slice(1).join("=")||"",q=()=>new URLSearchParams(location.search);
let attribution={};try{attribution=JSON.parse(localStorage.getItem(A)||"{}");if(!attribution.savedAt||Date.now()-attribution.savedAt>TTL)attribution={}}catch{}const current=q();U.forEach(k=>{const v=current.get(k);if(v)attribution[k]=v});if(U.some(k=>current.get(k))){attribution.savedAt=Date.now();try{localStorage.setItem(A,JSON.stringify(attribution))}catch{}}
const vid=cookie("tb_vid")||id();if(!cookie("tb_vid"))document.cookie="tb_vid="+vid+";path=/;max-age=31536000;SameSite=Lax";const fbp=cookie("_fbp"),fbclid=attribution.fbclid||"",fbc=cookie("_fbc")||(fbclid?"fb.1."+Date.now()+"."+fbclid:"");let lastPage="";
function send(eventName,data={}){const eventId=data.eventId||id(),payload={projectKey:K,eventName,eventId,eventTime:Math.floor(Date.now()/1000),url:location.href,referrer:document.referrer,visitorId:vid,fbclid,fbc,fbp,attribution,...data};const raw=JSON.stringify(payload);if(navigator.sendBeacon)navigator.sendBeacon(E,new Blob([raw],{type:"application/json"}));else fetch(E,{method:"POST",headers:{"content-type":"application/json"},body:raw,keepalive:true});if(window.fbq&&!/^(AdClick|PageError)$/.test(eventName))window.fbq("track",eventName,data,{eventID:eventId});return eventId}
function page(){const clean=location.pathname+location.search;if(clean===lastPage)return;lastPage=clean;send("PageView");send("ViewContent",{contentName:document.title})}
function decorate(element){const href=element.href||element.action;if(!href)return;try{const target=new URL(href,location.href);if(target.origin===location.origin&&!/checkout|pay|pagamento|comprar/i.test(target.pathname))return;U.forEach(k=>{if(attribution[k]&&!target.searchParams.has(k))target.searchParams.set(k,attribution[k])});target.searchParams.set("tb_vid",vid);if(fbp)target.searchParams.set("fbp",fbp);if(fbc)target.searchParams.set("fbc",fbc);if(element.href)element.href=target.toString();else element.action=target.toString()}catch{}}
function scan(){document.querySelectorAll("a[href],form[action]").forEach(decorate)}
window.TrackBase={track:send,pageView:page,viewContent:data=>send("ViewContent",data),lead:data=>send("Lead",data),initiateCheckout:data=>send("InitiateCheckout",data),purchase:data=>send("Purchase",data),attribution:()=>({...attribution}),decorateLinks:scan};if(fbclid||attribution.utm_source)send("AdClick");page();
addEventListener("error",event=>send("PageError",{message:String(event.message||"Erro de carregamento").slice(0,160)}));addEventListener("unhandledrejection",()=>send("PageError",{message:"Erro de execução"}));document.addEventListener("DOMContentLoaded",scan);new MutationObserver(scan).observe(document.documentElement,{childList:true,subtree:true});
document.addEventListener("click",event=>{const target=event.target.closest("a,button,[data-trackbase-event]");if(!target)return;decorate(target);const label=(target.href||"")+" "+(target.textContent||""),name=target.dataset.trackbaseEvent||(/checkout|comprar|buy|pix|pagamento/i.test(label)?"InitiateCheckout":"");if(name)send(name,{value:Number(target.dataset.value||0),currency:target.dataset.currency||"BRL",contentName:target.dataset.product||undefined})},true);
const push=history.pushState,replace=history.replaceState;history.pushState=function(){push.apply(this,arguments);queueMicrotask(page)};history.replaceState=function(){replace.apply(this,arguments);queueMicrotask(page)};addEventListener("popstate",page)})();`;
  return new Response(script,{headers:{"content-type":"application/javascript; charset=utf-8","cache-control":"public, max-age=300","access-control-allow-origin":"*"}})
}
