"use client";
import { useState } from "react";
import { Ban, Copy, Plus, RefreshCw, Trash2 } from "lucide-react";
import { useProjectProtection } from "@/components/use-project-protection";
import { copyText } from "@/lib/clipboard";
export function BlacklistClient() {
  const s = useProjectProtection();
  const [ip, setIp] = useState(""), [message, setMessage] = useState("");
  async function add(e: React.FormEvent) { e.preventDefault(); setMessage(""); if (await s.save("PATCH", { action: "add", ip })) { setIp(""); setMessage("IP salvo. Novos eventos desse endereço serão ignorados no servidor."); } }
  async function remove(value: string) { setMessage(""); if (await s.save("PATCH", { action: "remove", ip: value })) setMessage("IP removido. As próximas visitas podem gerar eventos novamente."); }
  async function copy() { if (await copyText(s.data?.blockedIps.join("\n") || "")) setMessage("Lista copiada para configurar no firewall da hospedagem."); else s.setError("Não foi possível copiar."); }
  return <div className="space-y-5">
    <section className="rounded-2xl border border-border bg-card p-5"><h2 className="flex items-center gap-2 text-lg font-semibold"><Ban className="size-5 text-red-500" />Excluir IPs do rastreamento</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Regras salvas na sua conta, por projeto. Os IPs são verificados no servidor antes de registrar novos eventos e enviar CAPI. A lista não bloqueia a abertura do site e não altera vendas confirmadas pelo gateway.</p><label className="mt-4 block text-sm">Projeto<select value={s.projectId} disabled={s.saving} onChange={e => { s.selectProject(e.target.value); setMessage(""); setIp(""); }} className="mt-1 w-full rounded-xl border border-border bg-background p-3"><option value="" disabled>Selecione seu projeto</option>{s.projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
    <form onSubmit={add} className="mt-4 flex flex-col gap-2 sm:flex-row"><label className="flex-1"><span className="sr-only">Endereço IPv4 ou IPv6</span><input value={ip} onChange={e => setIp(e.target.value)} maxLength={45} placeholder="IPv4 ou IPv6 completo" className="h-11 w-full rounded-xl border border-border bg-background px-3 text-sm" /></label><button disabled={s.saving || s.loading || !s.data || !ip.trim()} className="flex h-11 items-center justify-center gap-2 rounded-xl bg-red-600 px-4 text-sm text-white disabled:opacity-50"><Plus className="size-4" />Adicionar</button></form><p className="mt-3 text-xs leading-5 text-muted-foreground">Use um IP exato, sem porta ou /máscara. Para bloquear o acesso ao site inteiro, aplique a lista no firewall da hospedagem.</p></section>
    {s.error && <p role="alert" className="text-sm text-red-500">{s.error}</p>}{message && <p role="status" className="text-sm text-emerald-600 dark:text-emerald-400">{message}</p>}
    <section className="rounded-2xl border border-border bg-card p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h3 className="font-semibold">IPs excluídos ({s.data?.blockedIps.length || 0}/200)</h3><div className="flex gap-2"><button type="button" onClick={s.reload} disabled={!s.projectId || s.saving} className="rounded-lg border border-border p-2" aria-label="Recarregar lista"><RefreshCw className="size-4" /></button><button type="button" onClick={copy} disabled={!s.data?.blockedIps.length} className="inline-flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-sm disabled:opacity-50"><Copy className="size-4" />Copiar lista</button></div></div>
    {s.loading ? <p role="status" className="text-sm text-muted-foreground">Carregando…</p> : !s.projects.length ? <a className="text-red-500 underline" href="/projetos/novo">Crie um projeto para começar</a> : s.data?.blockedIps.length ? <ul className="space-y-2">{s.data.blockedIps.map(value => <li key={value} className="flex items-center justify-between gap-3 rounded-xl bg-background p-3"><code className="break-all text-sm">{value}</code><button type="button" onClick={() => remove(value)} disabled={s.saving} className="rounded-lg border border-border p-2 text-muted-foreground hover:text-red-500 disabled:opacity-50" aria-label={"Remover IP " + value}><Trash2 className="size-4" /></button></li>)}</ul> : <p className="text-sm text-muted-foreground">Nenhum IP excluído neste projeto.</p>}
    </section>
  </div>;
}
