"use client";
import {useEffect,useMemo,useState} from "react";
import {Area,AreaChart,Bar,BarChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {BarChart3,Bell,LayoutDashboard,Link2,Loader2,RefreshCw,TrendingDown,TrendingUp} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Card,CardContent} from "@/components/ui/card";
type Metrics={adClicks:number;pageViews:number;errors:number;viewContent:number;checkouts:number;sales:number;pending:number;pendingValue:number;gross:number;net:number;refunds:number;refundValue:number;chargebacks:number;chargebackValue:number;refundRate:number};
type Group={name:string;value:number;sales:number};type Dashboard={metrics:Metrics;daily:Array<{date:string;revenue:number;sales:number;pageViews:number;checkouts:number}>;hourly:Array<{hour:string;revenue:number;sales:number}>;products:Group[];sources:Group[];payments:Array<{name:string;approved:number;total:number;rate:number|null}>;countries:Group[];filters:{products:string[];sources:string[]};updatedAt?:string};type Meta={campaigns:Array<{spend:number;clicks:number}>;daily:Array<{date:string;spend:number}>};
const zero:Metrics={adClicks:0,pageViews:0,errors:0,viewContent:0,checkouts:0,sales:0,pending:0,pendingValue:0,gross:0,net:0,refunds:0,refundValue:0,chargebacks:0,chargebackValue:0,refundRate:0};const empty:Dashboard={metrics:zero,daily:[],hourly:[],products:[],sources:[],payments:[],countries:[],filters:{products:[],sources:[]}};
const money=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0),number=(v:number)=>new Intl.NumberFormat("pt-BR").format(v||0),pct=(v:number|null)=>v==null?"N/A":`${v.toFixed(1)}%`;
function Metric({label,value,tone="violet"}:{label:string;value:string;tone?:"violet"|"green"|"red"}){return <Card className="metric-card"><CardContent className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-sm text-slate-400">{label}</p><p className="mt-3 text-2xl font-semibold tracking-tight">{value}</p></div><div className={`rounded-lg p-2 ${tone==="green"?"bg-emerald-500/10 text-emerald-300":tone==="red"?"bg-rose-500/10 text-rose-300":"bg-violet-500/10 text-violet-300"}`}>{tone==="red"?<TrendingDown className="size-4"/>:<TrendingUp className="size-4"/>}</div></div></CardContent></Card>}
function Empty(){return <div className="py-10 text-center text-sm text-slate-500">Nenhum dado no período.</div>}
export function DashboardClient(){const[data,setData]=useState<Dashboard>(empty),[meta,setMeta]=useState<Meta>({campaigns:[],daily:[]}),[period,setPeriod]=useState("last_7d"),[source,setSource]=useState(""),[product,setProduct]=useState(""),[start,setStart]=useState(""),[end,setEnd]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const q=new URLSearchParams({period});if(source)q.set("source",source);if(product)q.set("product",product);if(period==="custom"){if(start)q.set("start",start);if(end)q.set("end",end)}const mp=period==="custom"?"last_7d":period,[a,b]=await Promise.all([fetch(`/api/dashboard?${q}`,{cache:"no-store"}),fetch(`/api/meta/campaigns?period=${mp}`,{cache:"no-store"})]),da=await a.json(),mb=await b.json();if(!a.ok)throw new Error(da.error||"Falha ao carregar dados.");setData({...empty,...da,metrics:{...zero,...da.metrics},filters:da.filters||empty.filters});setMeta(b.ok?mb:{campaigns:[],daily:[]})}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar.")}finally{setLoading(false)}};useEffect(()=>{load()},[period,source,product,start,end]);
 const spend=meta.campaigns.reduce((s,c)=>s+c.spend,0),clicks=meta.campaigns.reduce((s,c)=>s+c.clicks,0)||data.metrics.adClicks,profit=data.metrics.net-spend,roas=spend?data.metrics.net/spend:null,roi=spend?profit/spend*100:null,margin=data.metrics.net?profit/data.metrics.net*100:null,funnel=[{name:"Cliques",value:clicks},{name:"Vis. página",value:data.metrics.pageViews},{name:"ICs",value:data.metrics.checkouts},{name:"Vendas",value:data.metrics.sales}];const chart=useMemo(()=>{const map=new Map(data.daily.map(d=>[d.date,{...d,spend:0,profit:d.revenue}]));for(const d of meta.daily){const v=map.get(d.date)||{date:d.date,revenue:0,sales:0,pageViews:0,checkouts:0,spend:0,profit:0};v.spend+=d.spend;v.profit=v.revenue-v.spend;map.set(d.date,v)}return [...map.values()].sort((a,b)=>a.date.localeCompare(b.date))},[data.daily,meta.daily]);
 const cards=[["Lucro",money(profit),profit>=0?"green":"red"],["Gastos com anúncios",money(spend),"red"],["ROAS",roas==null?"N/A":`${roas.toFixed(2)}x`,"violet"],["Faturamento líquido",money(data.metrics.net),"green"],["Vendas pendentes",money(data.metrics.pendingValue),"violet"],["ROI",pct(roi),"violet"],["Custos de produto",money(0),"violet"],["Vendas reembolsadas",money(data.metrics.refundValue),"red"],["Margem",pct(margin),"violet"],["Taxas",money(0),"violet"],["Imposto total",money(0),"violet"],["Reembolso",pct(data.metrics.refundRate),"red"],["Despesas adicionais",money(0),"violet"],["Chargeback",data.metrics.sales?pct(data.metrics.chargebacks/data.metrics.sales*100):"0,0%","red"]] as const;
 return <main className="min-h-screen bg-[#080b12] text-slate-100"><aside className="fixed inset-y-0 z-20 hidden w-64 border-r border-white/7 bg-[#0b0e17] p-5 lg:block"><div className="flex items-center gap-3"><img src="/trackbase-logo.png" className="h-11 w-20 object-contain" alt="TrackBase Analytics"/><div><b>TrackBase Analytics</b><small className="block text-slate-500">Meta Ads Intelligence</small></div></div><nav className="mt-9 space-y-1">{[[LayoutDashboard,"Dashboard","/"],[Link2,"Integrações","/integracoes"],[BarChart3,"Campanhas","/campanhas"]].map(([Icon,label,href],i)=>{const I=Icon as typeof LayoutDashboard;return <a key={href as string} href={href as string} className={i?"nav-item":"nav-active"}><I/>{label as string}</a>})}</nav></aside><section className="lg:pl-64"><header className="sticky top-0 z-10 flex min-h-20 items-center justify-between border-b border-white/7 bg-[#080b12]/90 px-5 backdrop-blur lg:px-8"><div><h1 className="text-xl font-semibold">Resumo</h1><p className="text-sm text-slate-500">{data.updatedAt?`Atualizado ${new Date(data.updatedAt).toLocaleString("pt-BR")}`:"Carregando dados"}</p></div><div className="flex gap-2"><Button variant="outline" size="icon" onClick={load}>{loading?<Loader2 className="animate-spin"/>:<RefreshCw/>}</Button><Button variant="outline" size="icon"><Bell/></Button></div></header><div className="mx-auto max-w-[1600px] space-y-5 p-4 lg:p-7">
 <div className="metric-card grid gap-3 rounded-xl p-4 md:grid-cols-2 xl:grid-cols-5"><label className="text-sm text-slate-400"><span className="mb-1 block">Período de visualização</span><select className="dashboard-input" value={period} onChange={e=>setPeriod(e.target.value)}>{[["maximum","Máximo"],["today","Hoje"],["yesterday","Ontem"],["last_7d","Últimos 7 dias"],["last_30d","Últimos 30 dias"],["this_month","Este mês"],["last_month","Mês passado"],["custom","Personalizado"]].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{period==="custom"&&<><label className="text-sm text-slate-400"><span className="mb-1 block">Data inicial</span><input type="date" className="dashboard-input" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="text-sm text-slate-400"><span className="mb-1 block">Data final</span><input type="date" className="dashboard-input" value={end} onChange={e=>setEnd(e.target.value)}/></label></>}<label className="text-sm text-slate-400"><span className="mb-1 block">Fonte de tráfego</span><select className="dashboard-input" value={source} onChange={e=>setSource(e.target.value)}><option value="">Qualquer</option>{data.filters.sources.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm text-slate-400"><span className="mb-1 block">Produto</span><select className="dashboard-input" value={product} onChange={e=>setProduct(e.target.value)}><option value="">Qualquer</option>{data.filters.products.map(x=><option key={x}>{x}</option>)}</select></label></div>{error&&<div className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-4 text-sm text-rose-200">{error}</div>}
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4 2xl:grid-cols-7">{cards.map(([a,b,c])=><Metric key={a} label={a} value={b} tone={c}/>)}</div>
 <div className="grid gap-5 xl:grid-cols-2"><Card className="metric-card"><CardContent className="p-5"><h3 className="font-semibold">Funil de conversão (Meta Ads)</h3><div className="mt-6 grid grid-cols-4 gap-2">{funnel.map((f,i)=>{const rate=i?funnel[i-1].value?f.value/funnel[i-1].value*100:0:100;return <div key={f.name} className="text-center"><div className="relative mx-auto mb-4 flex h-28 items-end overflow-hidden rounded-lg bg-white/[.03]"><div className="w-full bg-gradient-to-t from-violet-600 to-sky-500" style={{height:`${Math.max(5,Math.min(100,rate))}%`}}/></div><b className="text-xl">{number(f.value)}</b><p className="mt-1 text-xs text-slate-400">{f.name}</p><p className="mt-1 text-xs text-violet-300">{rate.toFixed(1)}%</p></div>})}</div></CardContent></Card><Card className="metric-card"><CardContent className="p-5"><h3 className="font-semibold">Taxa de aprovação</h3><div className="mt-6 grid gap-3 sm:grid-cols-3">{data.payments.map(p=><div key={p.name} className="rounded-xl border border-white/8 p-5 text-center"><p className="text-sm text-slate-400">{p.name}</p><b className="mt-3 block text-2xl">{pct(p.rate)}</b><small className="text-slate-500">{p.approved}/{p.total} aprovadas</small></div>)}</div></CardContent></Card></div>
 <Card className="metric-card"><CardContent className="p-5"><h3 className="font-semibold">Faturamento × investimento × lucro por dia</h3><div className="mt-5 h-80">{chart.length?<ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><CartesianGrid stroke="#ffffff0b"/><XAxis dataKey="date" tick={{fill:"#78839a",fontSize:12}}/><YAxis tick={{fill:"#78839a",fontSize:12}}/><Tooltip contentStyle={{background:"#101521",border:"1px solid #ffffff18"}}/><Area type="monotone" dataKey="revenue" name="Faturamento" stroke="#23c7ff" fill="#23c7ff22"/><Area type="monotone" dataKey="spend" name="Investimento" stroke="#fb7185" fill="transparent"/><Area type="monotone" dataKey="profit" name="Lucro" stroke="#8b5cf6" fill="transparent"/></AreaChart></ResponsiveContainer>:<Empty/>}</div></CardContent></Card>
 <div className="grid gap-5 xl:grid-cols-2"><List title="Vendas por produto" rows={data.products}/><List title="Vendas por fonte" rows={data.sources}/></div><div className="grid gap-5 xl:grid-cols-2"><Card className="metric-card"><CardContent className="p-5"><h3 className="font-semibold">Vendas por horário</h3><div className="mt-5 h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.hourly}><CartesianGrid stroke="#ffffff0b"/><XAxis dataKey="hour" tick={{fill:"#78839a",fontSize:10}} interval={2}/><YAxis tick={{fill:"#78839a",fontSize:11}}/><Tooltip contentStyle={{background:"#101521",border:"1px solid #ffffff18"}}/><Bar dataKey="sales" name="Vendas" fill="#755cff" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></CardContent></Card><List title="Vendas por país" rows={data.countries}/></div>
 </div></section></main>}
function List({title,rows}:{title:string;rows:Group[]}){return <Card className="metric-card"><CardContent className="p-5"><h3 className="font-semibold">{title}</h3>{rows.length?<div className="mt-4 space-y-2">{rows.slice(0,10).map(x=><div key={x.name} className="flex justify-between gap-3 rounded-lg bg-white/[.025] p-3"><span className="truncate">{x.name}</span><b className="whitespace-nowrap">{x.sales} · {money(x.value)}</b></div>)}</div>:<Empty/>}</CardContent></Card>}
