"use client";
import { FeatureGuide } from "@/components/FeatureGuide";
import { ConversionFunnel } from "@/components/ConversionFunnel";
import { SetupBanner, type SetupProgress } from "@/components/SetupBanner";
import "./dashboard.css";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {Area,AreaChart,Bar,BarChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {Check,Loader2,RefreshCw,Settings2,Target,Wallet,ShoppingBag,ChartNoAxesCombined,Volume2} from "lucide-react";
import {Button} from "@/components/ui/button";
import {NotificationsBell} from "./notifications-bell";
import {SoundSidebar,SoundMobile} from "./sound-sidebar";
import {Card,CardContent} from "@/components/ui/card";
import {MobileMenu} from "@/components/MobileMenu";
import {FullMenu} from "@/components/FullMenu";
import {MobileTopBar} from "@/components/MobileTopBar";
import {AccountMenu, type AccountData} from "@/components/AccountMenu";
type Metrics={metaFunnel?:{pageViews:number;checkouts:number;initiated:number;sales:number};initiated?:number;adClicks:number;pageViews:number;errors:number;viewContent:number;checkouts:number;sales:number;pending:number;pendingValue:number;gross:number;net:number;refunds:number;refundValue:number;chargebacks:number;chargebackValue:number;refundRate:number};
type Group={name:string;value:number;sales:number};type Dashboard={metrics:Metrics;daily:Array<{date:string;revenue:number;sales:number;pageViews:number;checkouts:number}>;hourly:Array<{hour:string;revenue:number;sales:number}>;products:Group[];sources:Group[];payments:Array<{name:string;approved:number;total:number;rate:number|null}>;countries:Group[];filters:{products:string[];sources:string[]};updatedAt?:string};type Meta={campaigns:Array<{spend:number;clicks:number;impressions?:number;linkClicks?:number}>;daily:Array<{date:string;spend:number}>};
const zero:Metrics={adClicks:0,pageViews:0,errors:0,viewContent:0,checkouts:0,sales:0,pending:0,pendingValue:0,gross:0,net:0,refunds:0,refundValue:0,chargebacks:0,chargebackValue:0,refundRate:0};const empty:Dashboard={metrics:zero,daily:[],hourly:[],products:[],sources:[],payments:[],countries:[],filters:{products:[],sources:[]}};
const money=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0),number=(v:number)=>new Intl.NumberFormat("pt-BR").format(v||0),pct=(v:number|null)=>v==null?"N/A":`${v.toFixed(1)}%`;
function Metric({label,value,tone="violet",index=0}:{label:string;value:string;tone?:"violet"|"green"|"red";index?:number}) {
 const Icon=label.includes("Vendas")?ShoppingBag:label.includes("ROAS")||label.includes("Conversão")?ChartNoAxesCombined:Wallet;
 return <Card className="metric-card gs-metric" data-tone={tone} style={{animationDelay:`${Math.min(index,7)*35}ms`}}><CardContent className="p-5"><div className="gs-metric-heading"><p>{label}</p><span className="gs-metric-icon"><Icon size={17}/></span></div><p key={value} className="gs-metric-value" title={value}>{value}</p><div className="gs-metric-caption"><span/> {value==="Não configurado"?"Configuração pendente":"No período selecionado"}</div></CardContent></Card>;
}
function DashboardSkeleton(){return <div className="gs-skeleton-grid" role="status" aria-label="Carregando métricas">{Array.from({length:8},(_,i)=><div className="gs-skeleton" key={i}><span/><strong/><span/></div>)}</div>}
function Empty(){return <div className="py-10 text-center text-sm text-slate-500">Nenhum dado no período.</div>}
function RevenueGoals({revenue}:{revenue:number}){const goals=[1000,2000,3000,4000,5000,6000,7000,10000,20000,30000,50000,100000,200000,300000,500000,750000,1000000],reached=goals.filter(goal=>revenue>=goal),label=(goal:number)=>goal===1000000?"R$ 1 milhão":`R$ ${goal/1000} mil`,target=10000,progress=Math.min(100,Math.max(0,revenue/target*100));return <section className="metric-card gs-goals overflow-hidden rounded-xl"><div className="flex flex-wrap items-center justify-between gap-4 bg-blue-50 p-5"><div className="flex min-w-0 items-center gap-3"><div className="rounded-xl bg-blue-50 p-2.5 text-blue-600"><Target className="size-5"/></div><div><h2 className="font-semibold">Meta de faturamento</h2><p className="mt-1 text-sm text-slate-400">Acompanhe sua evolução até R$ 10 mil.</p></div></div><div className="text-right"><p className="text-xs uppercase tracking-wider text-slate-500">Meta do período</p><strong className="gs-revenue mt-1 block text-2xl">R$ 10 mil</strong><small className="text-slate-500">{money(revenue)} realizados</small></div></div><div className="border-t border-slate-200 p-5"><div className="mb-2 flex items-center justify-between gap-3 text-sm"><span className="text-slate-400">Progresso</span><b className="text-rose-300">{progress.toFixed(1)}%</b></div><div className="h-3 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-rose-700 via-rose-500 to-pink-300 transition-[width] duration-700" style={{width:`${progress}%`}}/></div></div>{reached.length>0?<div className="grid grid-cols-2 gap-2 border-t border-slate-200 p-5 sm:grid-cols-4 lg:grid-cols-6">{reached.map(goal=><div key={goal} className="flex min-h-16 items-center justify-center gap-2 rounded-lg border border-emerald-400/30 bg-emerald-400/10 px-3 py-2 text-center text-emerald-700"><Check className="size-4 shrink-0"/><b className="text-sm">{label(goal)}</b></div>)}</div>:null}</section>}

// Métricas do Dashboard escolhidas pela pessoa (botão "Personalizar
// métricas", salvo no navegador). Cada item calcula a partir do contexto `c`.
type DashCtx={m:Metrics;spend:number;clicks:number;linkClicks:number;impressions:number;profit:number};
type DashMetric={key:string;label:string;group:"Resultado"|"Vendas"|"Tráfego"|"Página";tone:"green"|"red"|"violet";def?:boolean;value:(c:DashCtx)=>number|null;fmt:"money"|"int"|"pct"|"x"};
const q=(a:number,b:number)=>b?a/b:null;
const DASH_METRICS:DashMetric[]=[
 {key:"profit",label:"Lucro",group:"Resultado",tone:"green",fmt:"money",def:true,value:c=>c.profit},
 {key:"net",label:"Faturamento líquido",group:"Resultado",tone:"green",fmt:"money",def:true,value:c=>c.m.net},
 {key:"gross",label:"Faturamento bruto",group:"Resultado",tone:"green",fmt:"money",value:c=>c.m.gross},
 {key:"spend",label:"Gastos com anúncios",group:"Resultado",tone:"red",fmt:"money",def:true,value:c=>c.spend},
 {key:"roas",label:"ROAS",group:"Resultado",tone:"violet",fmt:"x",def:true,value:c=>q(c.m.net,c.spend)},
 {key:"roi",label:"ROI",group:"Resultado",tone:"violet",fmt:"pct",def:true,value:c=>c.spend?c.profit/c.spend*100:null},
 {key:"margin",label:"Margem",group:"Resultado",tone:"violet",fmt:"pct",def:true,value:c=>c.m.net?c.profit/c.m.net*100:null},
 {key:"cpa",label:"CPA",group:"Resultado",tone:"red",fmt:"money",def:true,value:c=>q(c.spend,c.m.sales)},
 {key:"ticket",label:"Ticket médio",group:"Resultado",tone:"green",fmt:"money",def:true,value:c=>q(c.m.gross,c.m.sales)},
 {key:"profitPerSale",label:"Lucro por venda",group:"Resultado",tone:"green",fmt:"money",value:c=>q(c.profit,c.m.sales)},
 {key:"costInitiated",label:"Custo por venda iniciada",group:"Resultado",tone:"red",fmt:"money",value:c=>q(c.spend,c.m.initiated??0)},
 {key:"sales",label:"Vendas aprovadas",group:"Vendas",tone:"green",fmt:"int",def:true,value:c=>c.m.sales},
 {key:"initiated",label:"Vendas iniciadas",group:"Vendas",tone:"violet",fmt:"int",def:true,value:c=>c.m.initiated??null},
 {key:"approval",label:"Taxa de aprovação",group:"Vendas",tone:"green",fmt:"pct",def:true,value:c=>c.m.initiated?c.m.sales/c.m.initiated*100:null},
 {key:"pendingCount",label:"Vendas pendentes",group:"Vendas",tone:"violet",fmt:"int",value:c=>c.m.pending},
 {key:"pendingValue",label:"Valor pendente",group:"Vendas",tone:"violet",fmt:"money",def:true,value:c=>c.m.pendingValue},
 {key:"refunds",label:"Reembolsos",group:"Vendas",tone:"red",fmt:"int",value:c=>c.m.refunds},
 {key:"refundValue",label:"Valor reembolsado",group:"Vendas",tone:"red",fmt:"money",def:true,value:c=>c.m.refundValue},
 {key:"refundRate",label:"Taxa de reembolso",group:"Vendas",tone:"red",fmt:"pct",def:true,value:c=>c.m.refundRate},
 {key:"chargebacks",label:"Chargebacks",group:"Vendas",tone:"red",fmt:"int",value:c=>c.m.chargebacks},
 {key:"chargebackValue",label:"Valor em chargeback",group:"Vendas",tone:"red",fmt:"money",value:c=>c.m.chargebackValue},
 {key:"chargebackRate",label:"Taxa de chargeback",group:"Vendas",tone:"red",fmt:"pct",def:true,value:c=>c.m.sales?c.m.chargebacks/c.m.sales*100:0},
 {key:"impressions",label:"Impressões",group:"Tráfego",tone:"violet",fmt:"int",def:true,value:c=>c.impressions},
 {key:"cpm",label:"CPM",group:"Tráfego",tone:"red",fmt:"money",def:true,value:c=>c.impressions?c.spend/c.impressions*1000:null},
 {key:"allClicks",label:"Cliques (todos)",group:"Tráfego",tone:"violet",fmt:"int",value:c=>c.clicks},
 {key:"linkClicks",label:"Cliques no link",group:"Tráfego",tone:"violet",fmt:"int",def:true,value:c=>c.linkClicks},
 {key:"ctr",label:"CTR",group:"Tráfego",tone:"violet",fmt:"pct",def:true,value:c=>c.impressions?c.clicks/c.impressions*100:null},
 {key:"linkCtr",label:"CTR do link",group:"Tráfego",tone:"violet",fmt:"pct",value:c=>c.impressions?c.linkClicks/c.impressions*100:null},
 {key:"cpc",label:"CPC (link)",group:"Tráfego",tone:"red",fmt:"money",def:true,value:c=>q(c.spend,c.linkClicks)},
 {key:"cpcAll",label:"CPC (todos)",group:"Tráfego",tone:"red",fmt:"money",value:c=>q(c.spend,c.clicks)},
 {key:"pageViews",label:"Acessos",group:"Página",tone:"violet",fmt:"int",value:c=>c.m.pageViews},
 {key:"connect",label:"Taxa de conexão",group:"Página",tone:"green",fmt:"pct",def:true,value:c=>c.linkClicks?c.m.pageViews/c.linkClicks*100:null},
 {key:"costPageView",label:"Custo por acesso",group:"Página",tone:"red",fmt:"money",value:c=>q(c.spend,c.m.pageViews)},
 {key:"viewContent",label:"Visualizações de conteúdo",group:"Página",tone:"violet",fmt:"int",value:c=>c.m.viewContent},
 {key:"checkouts",label:"ICs",group:"Página",tone:"violet",fmt:"int",value:c=>c.m.checkouts},
 {key:"costCheckout",label:"Custo por IC",group:"Página",tone:"red",fmt:"money",def:true,value:c=>q(c.spend,c.m.checkouts)},
 {key:"pageToCheckout",label:"Conv. página → IC",group:"Página",tone:"green",fmt:"pct",value:c=>c.m.pageViews?c.m.checkouts/c.m.pageViews*100:null},
 {key:"checkoutToSale",label:"Conv. IC → venda",group:"Página",tone:"green",fmt:"pct",def:true,value:c=>c.m.checkouts?c.m.sales/c.m.checkouts*100:null},
 {key:"pageToSale",label:"Conv. página → venda",group:"Página",tone:"green",fmt:"pct",value:c=>c.m.pageViews?c.m.sales/c.m.pageViews*100:null},
 {key:"clickToSale",label:"Conv. clique → venda",group:"Página",tone:"green",fmt:"pct",value:c=>c.linkClicks?c.m.sales/c.linkClicks*100:null},
 {key:"errors",label:"Erros na página",group:"Página",tone:"red",fmt:"int",value:c=>c.m.errors},
];
const DASH_DEFAULT=DASH_METRICS.filter(m=>m.def).map(m=>m.key);
const DASH_KEY="gs_dashboard_metrics";
const DASH_GROUPS:{group:DashMetric["group"];desc:string}[]=[{group:"Resultado",desc:"Receita, mídia e rentabilidade no período."},{group:"Vendas",desc:"Pedidos, aprovação, pendências e estornos."},{group:"Tráfego",desc:"Custo e qualidade do clique no anúncio."},{group:"Página",desc:"Da visita ao checkout e à venda."}];
function formatDash(m:DashMetric,v:number|null){if(v==null||!Number.isFinite(v))return "N/A";if(m.fmt==="money")return money(v);if(m.fmt==="int")return number(v);if(m.fmt==="x")return `${v.toFixed(2)}x`;return `${v.toFixed(1)}%`}
function DashMetricPicker({value,onChange}:{value:string[];onChange:(k:string[])=>void}){
 const[open,setOpen]=useState(false);
 return <div className="relative"><Button variant="outline" size="sm" onClick={()=>setOpen(v=>!v)}><Settings2/>Personalizar métricas ({value.length})</Button>{open&&<div className="absolute right-0 z-40 mt-2 max-h-[70vh] w-80 overflow-y-auto rounded-xl border border-slate-200 bg-card p-3 shadow-2xl"><div className="mb-2 flex items-center justify-between"><b className="text-sm">Escolha as métricas</b><button type="button" className="text-xs text-blue-600" onClick={()=>onChange(DASH_DEFAULT)}>Padrão</button></div>{DASH_GROUPS.map(({group})=><div key={group} className="mb-2"><p className="mb-1 text-[11px] font-semibold uppercase tracking-wider text-slate-500">{group}</p>{DASH_METRICS.filter(m=>m.group===group).map(m=><label key={m.key} className="flex cursor-pointer items-center gap-2 rounded px-1 py-1 text-sm hover:bg-muted"><input type="checkbox" checked={value.includes(m.key)} onChange={e=>onChange(e.target.checked?DASH_METRICS.filter(x=>value.includes(x.key)||x.key===m.key).map(x=>x.key):value.filter(k=>k!==m.key))}/>{m.label}</label>)}</div>)}<Button size="sm" className="mt-1 w-full" onClick={()=>setOpen(false)}>Pronto</Button></div>}</div>;
}

export function DashboardClient({ accountData, setup = null }: { accountData: AccountData; setup?: SetupProgress | null }) {
  const [data,setData]=useState<Dashboard>(empty),[meta,setMeta]=useState<Meta>({campaigns:[],daily:[]}),[period,setPeriod]=useState("last_7d"),[source,setSource]=useState(""),[product,setProduct]=useState(""),[start,setStart]=useState(""),[end,setEnd]=useState(""),[appliedStart,setAppliedStart]=useState(""),[appliedEnd,setAppliedEnd]=useState(""),[autoRefresh,setAutoRefresh]=useState(0),[refreshKey,setRefreshKey]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const activeRequest=useRef<AbortController|null>(null);
  const [dashKeys,setDashKeys]=useState<string[]>(DASH_DEFAULT);
  useEffect(()=>{const t=window.setTimeout(()=>{try{const saved=JSON.parse(localStorage.getItem(DASH_KEY)||"null");if(Array.isArray(saved)&&saved.length)setDashKeys(saved.filter((k:string)=>DASH_METRICS.some(m=>m.key===k)))}catch{}},0);return()=>window.clearTimeout(t)},[]);
  const saveDashKeys=(keys:string[])=>{setDashKeys(keys);try{localStorage.setItem(DASH_KEY,JSON.stringify(keys))}catch{}};
  const load=useCallback(async()=>{activeRequest.current?.abort();const controller=new AbortController();activeRequest.current=controller;setLoading(true);setError("");try{const q=new URLSearchParams({period});if(source)q.set("source",source);if(product)q.set("product",product);if(period==="custom"){if(appliedStart)q.set("start",appliedStart);if(appliedEnd)q.set("end",appliedEnd)}const[a,b]=await Promise.all([fetch(`/api/dashboard?${q}`,{cache:"no-store",signal:controller.signal}),fetch(`/api/meta/campaigns?${q}`,{cache:"no-store",signal:controller.signal})]),da=await a.json(),mb=await b.json();if(!a.ok)throw new Error(da.error||"Falha ao carregar dados.");if(controller.signal.aborted)return;setData({...empty,...da,metrics:{...zero,...da.metrics},daily:Array.isArray(da.daily)?da.daily:[],hourly:Array.isArray(da.hourly)?da.hourly:[],products:Array.isArray(da.products)?da.products:[],sources:Array.isArray(da.sources)?da.sources:[],payments:Array.isArray(da.payments)?da.payments:[],countries:Array.isArray(da.countries)?da.countries:[],filters:da.filters||empty.filters});setMeta(b.ok&&mb?{campaigns:Array.isArray(mb.campaigns)?mb.campaigns:[],daily:Array.isArray(mb.daily)?mb.daily:[]}:{campaigns:[],daily:[]})}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:"Falha ao carregar.")}finally{if(!controller.signal.aborted)setLoading(false)}},[period,source,product,appliedStart,appliedEnd]);useEffect(()=>{const timer=setTimeout(()=>void load(),100);return()=>{clearTimeout(timer);activeRequest.current?.abort()}},[load,refreshKey]);useEffect(()=>{if(!autoRefresh)return;const timer=setInterval(()=>{if(document.visibilityState==="visible")setRefreshKey(v=>v+1)},autoRefresh*1000);return()=>clearInterval(timer)},[autoRefresh]);
  const applyDates=()=>{if(period==="custom"){setAppliedStart(start);setAppliedEnd(end)}else setRefreshKey(v=>v+1)};const reset=()=>{setPeriod("last_7d");setSource("");setProduct("");setStart("");setEnd("");setAppliedStart("");setAppliedEnd("");setAutoRefresh(0);setRefreshKey(v=>v+1)};
  const spend=meta.campaigns.reduce((s,c)=>s+c.spend,0),clicks=meta.campaigns.reduce((s,c)=>s+c.clicks,0)||data.metrics.adClicks,impressions=meta.campaigns.reduce((s,c)=>s+(c.impressions||0),0),linkClicks=meta.campaigns.reduce((s,c)=>s+(c.linkClicks||0),0)||clicks,profit=data.metrics.net-spend,mf=data.metrics.metaFunnel,funnel=[{name:"Cliques",hint:"Cliques no link do anúncio (Meta)",value:linkClicks},{name:"Vis. Página",hint:"Pessoas vindas do Meta que abriram a página",value:mf?.pageViews??0},{name:"ICs",hint:"Pessoas vindas do Meta que iniciaram o checkout",value:mf?.checkouts??0},{name:"Vendas Inic.",hint:"Pedidos com UTM do Meta (Pix gerado, boleto…)",value:mf?.initiated??0},{name:"Vendas Apr.",hint:"Pagamentos aprovados com UTM do Meta",value:mf?.sales??0}];const dashCtx:DashCtx={m:data.metrics,spend,clicks,linkClicks,impressions,profit};const chart=useMemo(()=>{const map=new Map(data.daily.map(d=>[d.date,{...d,spend:0,profit:d.revenue}]));for(const d of meta.daily){const v=map.get(d.date)||{date:d.date,revenue:0,sales:0,pageViews:0,checkouts:0,spend:0,profit:0};v.spend+=d.spend;v.profit=v.revenue-v.spend;map.set(d.date,v)}return [...map.values()].sort((a,b)=>a.date.localeCompare(b.date))},[data.daily,meta.daily]);
  const costCards=[["Custos de produto","Não configurado","violet"],["Taxas","Não configurado","violet"],["Imposto total","Não configurado","violet"],["Despesas adicionais","Não configurado","violet"]] as const;
  return <main className="gs-dashboard min-h-screen"><aside className="fixed inset-y-0 z-20 hidden w-64 flex-col border-r border-slate-200 bg-card p-5 lg:flex"><div className="flex shrink-0 items-center gap-3"><img src="/ghostscale-logo.png" className="h-11 w-auto object-contain" alt="GhostScale"/><div><small className="block text-slate-500">Visão completa da operação</small></div></div><nav className="mt-9 min-h-0 flex-1 space-y-1 overflow-y-auto pb-4"><FullMenu/><SoundSidebar/></nav></aside><section className="lg:pl-64"><div className="sticky top-0 z-20 border-b border-slate-200 bg-card/95 px-4 py-3 backdrop-blur lg:hidden"><MobileTopBar accountData={accountData}/></div><header className="sticky top-0 z-10 hidden min-h-20 flex-wrap items-center justify-between border-b border-slate-200 bg-card/80 px-5 backdrop-blur lg:flex lg:px-8"><div><h1 className="text-2xl font-semibold">Visão geral</h1><p className="text-sm text-slate-500">{data.updatedAt?`Atualizado ${new Date(data.updatedAt).toLocaleString("pt-BR")}`:"Carregando dados"}</p></div><div className="flex items-center gap-2"><span className="hidden text-right sm:block">{accountData.isAdmin ? <b className="block text-sm font-medium text-slate-900">{accountData.workspaceName}</b> : <b className="block text-sm font-medium text-slate-900">{accountData.userName}</b>}<small className="text-xs text-slate-500">{accountData.planName} · {accountData.planStatus === "active" ? "Ativo" : accountData.planStatus === "demo" ? "Modo demonstração" : accountData.planStatus}</small></span><div className="grid size-9 place-items-center rounded-full bg-gradient-to-br from-rose-700 to-red-500 text-sm font-semibold text-white">{accountData.avatarInitial}</div><Button variant="outline" size="icon" aria-label="Atualizar métricas" disabled={loading} onClick={load}>{loading?<Loader2 className="animate-spin"/>:<RefreshCw/>}</Button><a href="/configuracoes#som" title="Sons de venda" aria-label="Sons de venda" className="inline-flex size-9 items-center justify-center rounded-lg border border-slate-200 text-slate-500 transition hover:border-blue-300 hover:text-blue-600"><Volume2 className="size-4"/></a><NotificationsBell/><AccountMenu data={accountData}/></div></header><div className="border-b border-slate-200 bg-card px-4 py-2 lg:hidden"><MobileMenu/></div><SoundMobile/><div className="gs-content mx-auto max-w-[1600px] space-y-6 p-5 lg:p-9"><FeatureGuide/><SetupBanner setup={setup}/>{loading?<DashboardSkeleton/>:error?<div className="rounded-xl border border-red-300 bg-red-50 p-4 text-red-600">{error} <Button variant="outline" size="sm" onClick={load}>Tentar novamente</Button></div>:
  <><div className="metric-card rounded-xl p-4"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><label className="text-sm text-slate-400"><span className="mb-1 block">Período de visualização</span><select className="dashboard-input" value={period} onChange={e=>setPeriod(e.target.value)}>{[["maximum","Todo o período"],["today","Hoje"],["yesterday","Ontem"],["last_7d","Últimos 7 dias"],["last_30d","Últimos 30 dias"],["this_month","Este mês"],["last_month","Mês passado"],["custom","Personalizado"]].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{period==="custom"&&<><label className="text-sm text-slate-400"><span className="mb-1 block">Data inicial</span><input type="date" className="dashboard-input" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="text-sm text-slate-400"><span className="mb-1 block">Data final</span><input type="date" className="dashboard-input" value={end} onChange={e=>setEnd(e.target.value)}/></label></>}<label className="text-sm text-slate-400"><span className="mb-1 block">Fonte de tráfego</span><select className="dashboard-input" value={source} onChange={e=>setSource(e.target.value)}><option value="">Qualquer</option>{data.filters.sources.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm text-slate-400"><span className="mb-1 block">Produto</span><select className="dashboard-input" value={product} onChange={e=>setProduct(e.target.value)}><option value="">Qualquer</option>{data.filters.products.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm text-slate-400"><span className="mb-1 block">Atualização automática</span><select className="dashboard-input" value={autoRefresh} onChange={e=>setAutoRefresh(Number(e.target.value))}><option value="0">Desativada</option><option value="30">A cada 30 segundos</option><option value="60">A cada 1 minuto</option><option value="300">A cada 5 minutos</option></select></label></div><div className="gs-filter-actions">{period==="custom"&&<Button disabled={!start||!end||start>end} onClick={applyDates}>Aplicar período</Button>}<button onClick={reset}>Limpar filtros</button><span>Valores em BRL · período selecionado</span></div></div>
  {DASH_GROUPS.filter(g=>g.group!=="Vendas").map(({group,desc},gi)=>{const items=DASH_METRICS.filter(m=>m.group===group&&dashKeys.includes(m.key));if(!items.length&&gi)return null;return <section key={group}><div className="mb-3 flex flex-wrap items-end justify-between gap-2"><div><h2 className="text-base font-semibold">{group}</h2><p className="text-sm text-slate-500">{desc}</p></div>{gi===0&&<DashMetricPicker value={dashKeys} onChange={saveDashKeys}/>}</div><div className="gs-results-grid">{items.map((m,i)=><Metric key={m.key} label={m.label} value={formatDash(m,m.value(dashCtx))} tone={m.key==="profit"?(dashCtx.profit>=0?"green":"red"):m.tone} index={i}/>)}</div></section>})}<div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><section><div className="mb-3"><h2 className="text-base font-semibold">Vendas</h2><p className="text-sm text-slate-500">Pedidos, aprovação, pendências e estornos.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{DASH_METRICS.filter(m=>m.group==="Vendas"&&dashKeys.includes(m.key)).map(m=><Metric key={m.key} label={m.label} value={formatDash(m,m.value(dashCtx))} tone={m.tone}/>)}</div></section><section><div className="mb-3"><h2 className="text-base font-semibold">Custos</h2><p className="text-sm text-slate-500">O lucro mostrado é o faturamento líquido menos o gasto com anúncios.</p></div><Card className="metric-card"><CardContent className="p-5"><ul className="space-y-2">{costCards.map(([a])=><li key={a} className="flex items-center justify-between gap-3 rounded-lg bg-muted/50 px-3 py-2.5 text-sm"><span>{a}</span><span className="text-xs text-slate-500">Fora do cálculo</span></li>)}</ul></CardContent></Card></section></div>
  <div className="grid gap-5 xl:grid-cols-2"><Card className="metric-card gs-funnel-card overflow-hidden xl:col-span-2"><CardContent className="p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className="gs-section-dot"/><h3 className="font-semibold">Funil de conversão</h3></div><p className="mt-1 text-xs text-slate-400">Só tráfego com UTM do Meta · do clique até a venda</p></div><span className="gs-live-badge"><i/>Ao vivo</span></div><ConversionFunnel stages={funnel}/></CardContent></Card><Card className="metric-card"><CardContent className="p-5"><h3 className="font-semibold">Taxa de aprovação</h3><div className="mt-6 grid gap-3 sm:grid-cols-3">{data.payments.map(p=><div key={p.name} className="rounded-xl border border-slate-200 p-5 text-center"><p className="text-sm text-slate-400">{p.name}</p><b className="mt-3 block text-2xl">{pct(p.rate)}</b><small className="text-slate-500">{p.approved}/{p.total} aprovadas</small></div>)}</div></CardContent></Card></div>
  <Card className="metric-card"><CardContent className="p-5"><h3 className="font-semibold">Faturamento × investimento × lucro por dia</h3><div className="mt-5 h-80">{chart.length?<ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><defs><linearGradient id="gs-revenue-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#fb7185" stopOpacity={0.25}/><stop offset="100%" stopColor="#fb7185" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="rgba(148,163,184,.12)"/><XAxis dataKey="date" tick={{fill:"#94a3b8",fontSize:12}}/><YAxis tick={{fill:"#94a3b8",fontSize:12}}/><Tooltip contentStyle={{background:"var(--popover)",border:"1px solid var(--border)",borderRadius:10,color:"var(--popover-foreground)"}}/><Area isAnimationActive={false} strokeWidth={2} type="monotone" dataKey="revenue" name="Faturamento" stroke="#fb7185" fill="url(#gs-revenue-fill)"/><Area isAnimationActive={false} strokeWidth={2} type="monotone" dataKey="spend" name="Investimento" stroke="#f59e0b" fill="transparent"/><Area isAnimationActive={false} strokeWidth={2} type="monotone" dataKey="profit" name="Lucro" stroke="#16a34a" fill="transparent"/></AreaChart></ResponsiveContainer>:<Empty/>}</div></CardContent></Card>
  <RevenueGoals revenue={data.metrics.gross}/><div className="grid gap-5 xl:grid-cols-2"><List title="Vendas por produto" rows={data.products}/><List title="Vendas por fonte" rows={data.sources}/></div><div className="grid gap-5 xl:grid-cols-2"><Card className="metric-card"><CardContent className="p-5"><h3 className="font-semibold">Vendas por horário</h3><div className="mt-5 h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.hourly}><CartesianGrid vertical={false} stroke="rgba(148,163,184,.12)"/><XAxis dataKey="hour" tick={{fill:"#94a3b8",fontSize:10}} interval={2}/><YAxis tick={{fill:"#94a3b8",fontSize:11}}/><Tooltip contentStyle={{background:"var(--popover)",border:"1px solid var(--border)",borderRadius:10,color:"var(--popover-foreground)"}}/><Bar isAnimationActive={false} dataKey="sales" name="Vendas" fill="#fb7185" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></CardContent></Card><List title="Vendas por país" rows={data.countries}/></div>
  </>}</div></section></main>}
function List({title,rows}:{title:string;rows:Group[]}){return <Card className="metric-card"><CardContent className="p-5"><h3 className="font-semibold">{title}</h3>{rows.length?<div className="mt-4 space-y-2">{rows.slice(0,10).map(x=><div key={x.name} className="flex justify-between gap-3 rounded-lg bg-muted/50 p-3"><span className="truncate">{x.name}</span><b className="whitespace-nowrap">{x.sales} · {money(x.value)}</b></div>)}</div>:<Empty/>}</CardContent></Card>}
