import { BarChart3, Bell, LayoutDashboard, Link2, Radio } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { requireChatGPTUser } from "./chatgpt-auth";

const metrics=[["Investimento","R$ 1.284,50","+12,8%"],["Faturamento","R$ 4.761,20","+24,6%"],["Vendas","48","+17,1%"],["ROAS","3,71x","+10,4%"]];
const campaigns=[
["LATAM • JetHose • CBO","R$ 482,30","1.842","128","19","R$ 25,38","R$ 1.912,40","3,96x"],
["Ferramentas • Escala 01","R$ 396,80","1.274","94","16","R$ 24,80","R$ 1.638,40","4,13x"],
["Kit Bíblico • Criativos","R$ 251,40","906","52","9","R$ 27,93","R$ 782,10","3,11x"],
["Remarketing • 7 dias","R$ 154,00","388","31","4","R$ 38,50","R$ 428,30","2,78x"]];
const nav=[[LayoutDashboard,"Dashboard","/"],[Link2,"Integrações","/integracoes"],[BarChart3,"Campanhas","/campanhas"]];

function Logo(){return <div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-violet-600 shadow-[0_0_28px_#755cff55]"><Radio className="size-5"/></div><div><b>TrackBase Analytics</b><small className="block text-slate-500">Meta Ads Intelligence</small></div></div>}
export const dynamic = "force-dynamic";
export default async function Home(){await requireChatGPTUser("/");return <main className="min-h-screen bg-[#080b12] text-slate-100">
<aside className="fixed inset-y-0 hidden w-64 border-r border-white/7 bg-[#0b0e17] p-5 lg:block"><Logo/><nav className="mt-9 space-y-1">{nav.map(([Icon,label,href],i)=>{const I=Icon as typeof LayoutDashboard;return <a href={href as string} key={label as string} className={i?"nav-item":"nav-active"}><I/>{label as string}</a>})}</nav><div className="absolute bottom-5 left-5 right-5"><div className="rounded-xl border border-white/7 p-3"><b className="text-sm">Kit Bíblico</b><small className="block text-slate-500">Administrador</small></div></div></aside>
<section className="lg:pl-64"><header className="flex h-20 items-center justify-between border-b border-white/7 px-5 lg:px-8"><div><h1 className="text-xl font-semibold">Dashboard</h1><p className="hidden text-sm text-slate-500 sm:block">Resultados consolidados dos seus anúncios</p></div><div className="flex gap-3"><a href="/integracoes"><Badge className="bg-amber-500/10 text-amber-300">● Configuração necessária</Badge></a><Button variant="outline" size="icon"><Bell className="size-4"/></Button></div></header>
<div className="mx-auto max-w-[1500px] p-5 lg:p-8"><div className="mb-6 flex items-end justify-between"><div><h2 className="text-2xl font-semibold">Performance</h2><p className="text-sm text-slate-500">Atribuição por UTMs, fbclid, Pixel e CAPI.</p></div><a href="/integracoes" className="rounded-lg border border-white/10 px-4 py-2 text-sm hover:bg-white/5">Conectar Pixel</a></div>
<div className="mb-4 rounded-xl border border-amber-400/15 bg-amber-400/[.06] px-4 py-3 text-sm text-amber-200"><b>Demonstração:</b> os números abaixo serão substituídos pelos seus eventos reais.</div>
<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(m=><Card className="metric-card" key={m[0]}><CardContent className="p-5"><div className="flex justify-between text-sm"><span className="text-slate-400">{m[0]}</span><span className="text-emerald-400">{m[2]}</span></div><div className="mt-3 text-2xl font-semibold">{m[1]}</div><div className="mt-4 h-1 rounded bg-white/5"><div className="h-full w-2/3 rounded bg-gradient-to-r from-violet-600 to-sky-400"/></div></CardContent></Card>)}</div>
<div className="mt-5 grid gap-5 xl:grid-cols-[1.55fr_.85fr]"><Card className="metric-card"><CardContent className="p-5"><h3 className="font-semibold">Faturamento x investimento</h3><p className="text-sm text-slate-500">Últimos sete dias</p><div className="mt-6 flex h-56 items-end gap-3">{[42,58,48,72,65,88,79].map((h,i)=><div key={i} className="flex flex-1 items-end justify-center gap-1"><div className="w-2/5 rounded-t bg-violet-500" style={{height:h+"%"}}/><div className="w-2/5 rounded-t bg-sky-400" style={{height:h/3+"%"}}/></div>)}</div></CardContent></Card>
<Card className="metric-card"><CardContent className="p-5"><h3 className="font-semibold">Funil de conversão</h3><p className="mb-6 text-sm text-slate-500">Da visita até a compra</p>{[["PageView","4.892",100],["ViewContent","3.941",81],["InitiateCheckout","305",39],["Purchase","48",16]].map(x=><div className="mb-5" key={x[0]}><div className="mb-2 flex justify-between text-sm"><span>{x[0]}</span><b>{x[1]}</b></div><Progress value={x[2] as number} className="h-2"/></div>)}</CardContent></Card></div>
<Card className="metric-card mt-5 overflow-hidden"><CardContent className="p-0"><div className="border-b border-white/7 p-5"><h3 className="font-semibold">Campanhas</h3><p className="text-sm text-slate-500">Resultado atribuído por campanha</p></div><div className="overflow-x-auto"><table className="w-full min-w-[950px] text-sm"><thead><tr>{["Campanha","Gasto","Visitas","IC","Vendas","CPA","Faturamento","ROAS"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{campaigns.map(r=><tr key={r[0]}>{r.map((v,i)=><td key={i} className={i===7?"text-emerald-400":""}>{v}</td>)}</tr>)}</tbody></table></div></CardContent></Card></div></section></main>}
