import { BarChart3, Bell, LayoutDashboard, Link2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { requireChatGPTUser } from "./chatgpt-auth";

const metrics=[["Cliques no anúncio","0","Meta/UTM"],["Acessos à página","0","PageView"],["Erros de acesso","0","Falhas"],["Inícios de checkout","0","IC"],["Compras aprovadas","0","Purchase"]];
const campaigns:string[][]=[];
const nav=[[LayoutDashboard,"Dashboard","/"],[Link2,"Integrações","/integracoes"],[BarChart3,"Campanhas","/campanhas"]];

function Logo(){return <div className="flex items-center gap-3"><img src="/trackbase-logo.png" alt="Logo TrackBase Analytics" className="h-11 w-20 shrink-0 object-contain"/><div><b>TrackBase Analytics</b><small className="block text-slate-500">Meta Ads Intelligence</small></div></div>}
export const dynamic = "force-dynamic";
export default async function Home(){await requireChatGPTUser("/");return <main className="min-h-screen bg-[#080b12] text-slate-100">
<aside className="fixed inset-y-0 hidden w-64 border-r border-white/7 bg-[#0b0e17] p-5 lg:block"><Logo/><nav className="mt-9 space-y-1">{nav.map(([Icon,label,href],i)=>{const I=Icon as typeof LayoutDashboard;return <a href={href as string} key={label as string} className={i?"nav-item":"nav-active"}><I/>{label as string}</a>})}</nav><div className="absolute bottom-5 left-5 right-5"><div className="rounded-xl border border-white/7 p-3"><b className="text-sm">Kit Bíblico</b><small className="block text-slate-500">Administrador</small></div></div></aside>
<section className="lg:pl-64"><header className="flex h-20 items-center justify-between border-b border-white/7 px-5 lg:px-8"><div><h1 className="text-xl font-semibold">Dashboard</h1><p className="hidden text-sm text-slate-500 sm:block">Resultados consolidados dos seus anúncios</p></div><div className="flex gap-3"><a href="/integracoes"><Badge className="bg-amber-500/10 text-amber-300">● Configuração necessária</Badge></a><Button variant="outline" size="icon"><Bell className="size-4"/></Button></div></header>
<div className="mx-auto max-w-[1500px] p-5 lg:p-8"><div className="mb-6 flex items-end justify-between"><div><h2 className="text-2xl font-semibold">Performance</h2><p className="text-sm text-slate-500">Atribuição por UTMs, fbclid, Pixel e CAPI.</p></div><a href="/integracoes" className="rounded-lg border border-white/10 px-4 py-2 text-sm hover:bg-white/5">Conectar Pixel</a></div>
<div className="mb-4 rounded-xl border border-violet-400/15 bg-violet-400/[.06] px-4 py-3 text-sm text-violet-200">Os números começam em zero e aumentam somente quando a TrackBase recebe eventos reais.</div>
<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{metrics.map(m=><Card className="metric-card" key={m[0]}><CardContent className="p-5"><div className="flex justify-between gap-2 text-sm"><span className="text-slate-400">{m[0]}</span><span className="text-violet-300">{m[2]}</span></div><div className="mt-3 text-3xl font-semibold">{m[1]}</div><p className="mt-3 text-xs text-slate-500">Aguardando eventos reais</p></CardContent></Card>)}</div>
<div className="mt-5 grid gap-5 xl:grid-cols-[.85fr_1.55fr]"><Card className="metric-card"><CardContent className="p-5"><h3 className="font-semibold">Qualidade dos acessos</h3><p className="text-sm text-slate-500">Diferença entre o clique e a página carregada</p><div className="mt-6 space-y-4 text-sm"><div className="flex justify-between rounded-lg bg-white/[.03] p-4"><span>Cliques sem PageView</span><b>0</b></div><div className="flex justify-between rounded-lg bg-white/[.03] p-4"><span>Taxa de carregamento</span><b>N/A</b></div><div className="flex justify-between rounded-lg bg-white/[.03] p-4"><span>Erros capturados</span><b>0</b></div></div></CardContent></Card>
<Card className="metric-card"><CardContent className="p-5"><h3 className="font-semibold">Funil de conversão</h3><p className="mb-6 text-sm text-slate-500">Do clique até a compra aprovada</p>{[["Cliques","0",0],["Acessos à página","0",0],["Erros de acesso","0",0],["Inícios de checkout","0",0],["Compras aprovadas","0",0]].map(x=><div className="mb-4" key={x[0]}><div className="mb-2 flex justify-between text-sm"><span>{x[0]}</span><b>{x[1]}</b></div><Progress value={x[2] as number} className="h-2"/></div>)}</CardContent></Card></div>
<Card className="metric-card mt-5 overflow-hidden"><CardContent className="p-0"><div className="border-b border-white/7 p-5"><h3 className="font-semibold">Campanhas</h3><p className="text-sm text-slate-500">Cliques, acessos, checkouts e compras por campanha</p></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr>{["Campanha","Cliques","Acessos","Erros","ICs","Compras","Conversão"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{campaigns.length?campaigns.map(r=><tr key={r[0]}>{r.map((v,i)=><td key={i}>{v}</td>)}</tr>):<tr><td colSpan={7} className="py-10 text-center text-slate-500">Nenhuma campanha rastreada ainda.</td></tr>}</tbody></table></div></CardContent></Card></div></section></main>}
