import {
  LayoutDashboard,
  PlusSquare,
  Megaphone,
  FlaskConical,
  ShoppingCart,
  Activity,
  BarChart3,
  Tags,
  Filter,
  Flame,
  Sparkles,
  GitBranch,
  Bot,
  ShieldCheck,
  Ban,
  ShieldAlert,
  MonitorCheck,
  Trophy,
  MessagesSquare,
  UserRound,
  CreditCard,
  Plug,
  Landmark,
  Beaker,
  ContactRound,
  Radio,
  Link,
  Calculator,
  Network,
  ListChecks,
  Webhook,
  BookOpen,
  Users,
  Settings,
  MessageSquareText,
  Zap,
  Factory,
  TrendingUp,
  ArrowUpRight,
  Shield,
  Search,
  Layers,
  Grid,
  FileText,
  HelpCircle,
  ChevronDown,
} from "lucide-react";

export type NavItem = { label: string; href: string; icon: React.ComponentType<{ className?: string }>; badge?: string };
export type NavGroup = { title: string; items: NavItem[] };

export const NAV_GROUPS: NavGroup[] = [
  {
    title: "Visão geral",
    items: [
      { label: "Dashboard", href: "/", icon: LayoutDashboard },
      { label: "Novo Projeto", href: "/projetos/novo", icon: PlusSquare },
      { label: "Campanhas", href: "/campanhas", icon: Megaphone },
      { label: "Meta Lab", href: "/meta-lab", icon: FlaskConical },
      { label: "Vendas", href: "/vendas", icon: ShoppingCart },
      { label: "Eventos", href: "/eventos", icon: Activity },
    ],
  },
  {
    title: "Análise e Otimização",
    items: [
      { label: "Relatórios", href: "/relatorios", icon: BarChart3 },
      { label: "Relatórios de UTMs", href: "/relatorios/utms", icon: Tags },
      { label: "Análise de Funil", href: "/funil", icon: Filter },
      { label: "Heatmaps", href: "/heatmaps", icon: Flame },
      { label: "Predict (IA)", href: "/predict", icon: Sparkles, badge: "IA" },
      { label: "Atribuição", href: "/atribuicao", icon: GitBranch },
      { label: "Agent Hub", href: "/agent-hub", icon: Bot },
    ],
  },
  {
    title: "Segurança",
    items: [
      { label: "Anti-Clone", href: "/seguranca/anti-clone", icon: ShieldCheck },
      { label: "Blacklist de IP", href: "/seguranca/blacklist", icon: Ban },
      { label: "Tráfego Inválido", href: "/seguranca/trafego-invalido", icon: ShieldAlert },
      { label: "Monitoramento de Sites", href: "/seguranca/monitoramento", icon: MonitorCheck },
    ],
  },
  {
    title: "Integrações",
    items: [
      { label: "Integrações", href: "/integracoes", icon: Plug },
      { label: "Gateways", href: "/integracoes/gateways", icon: Landmark },
      { label: "Offer Lab", href: "/offer-lab", icon: Beaker },
      { label: "Contas Meta", href: "/contas-meta", icon: ContactRound },
      { label: "Pixel & CAPI", href: "/pixel-capi", icon: Radio },
    ],
  },
  {
    title: "Ferramentas",
    items: [
      { label: "UTM Builder", href: "/ferramentas/utm-builder", icon: Link },
      { label: "Calculadoras", href: "/ferramentas/calculadora-roas", icon: Calculator },
      { label: "CPA Máximo", href: "/ferramentas/cpa-maximo", icon: TrendingUp },
      { label: "Nomes de Campanha", href: "/ferramentas/nomes-campanha", icon: FileText },
      { label: "Mapa de Links", href: "/ferramentas/mapa-links", icon: Network },
      { label: "Checklist Campanha", href: "/ferramentas/checklist", icon: ListChecks },
      { label: "Ativador Pixel TikTok", href: "/ferramentas/ativador-tiktok", icon: Zap },
      { label: "Webhooks", href: "/webhooks", icon: Webhook },
    ],
  },
  {
    title: "Comunidade",
    items: [
      { label: "Rankings", href: "/comunidade/rankings", icon: Trophy },
      { label: "Chat e Clubes", href: "/comunidade/chat", icon: MessagesSquare },
      { label: "Documentação", href: "/docs", icon: BookOpen },
      { label: "Feedback", href: "/feedback", icon: MessageSquareText },
    ],
  },
  {
    title: "Conta e Sistema",
    items: [
      { label: "Meu Perfil", href: "/conta/perfil", icon: UserRound },
      { label: "Assinatura", href: "/conta/assinatura", icon: CreditCard },
      { label: "Assinatura Avançado", href: "/conta/assinatura-avancada", icon: Factory, badge: "TikTok + Meta" },
      { label: "Equipe", href: "/equipe", icon: Users },
      { label: "Configurações", href: "/configuracoes", icon: Settings },
      { label: "Ajuda", href: "/docs/faq", icon: HelpCircle },
    ],
  },
];

export const ALL_NAV_HREFS = NAV_GROUPS.flatMap((g) => g.items.map((i) => i.href));
