import { and,eq } from "drizzle-orm";
import { ensureDb,getDb } from "@/db";
import { metaAccounts,metaLinked } from "@/db/schema";
import { metaConfig } from "@/lib/meta";
import { hasActivePlan, planRequiredResponse, requestUserId } from "@/lib/trackbase-security";
export const dynamic="force-dynamic";
export async function GET(request:Request){try{const userId=await requestUserId(request);if(!userId)return Response.json({error:"Não autenticado."},{status:401});await ensureDb();const db=getDb();const rows=await db.select({id:metaAccounts.id,adAccountId:metaAccounts.adAccountId,name:metaAccounts.accountName,metaUserName:metaAccounts.metaUserName,currency:metaAccounts.currency,timezoneName:metaAccounts.timezoneName,accountStatus:metaAccounts.accountStatus,tokenExpiresAt:metaAccounts.tokenExpiresAt,connectedAt:metaAccounts.connectedAt}).from(metaAccounts).where(eq(metaAccounts.userId,userId));const links=await db.select({adAccountId:metaLinked.adAccountId}).from(metaLinked).where(eq(metaLinked.userId,userId));const linked=new Set(links.map(l=>l.adAccountId));const config=metaConfig();const accounts=rows.map(r=>({...r,selected:linked.has(r.adAccountId)}));accounts.sort((a,b)=>Number(b.selected)-Number(a.selected)||a.name.localeCompare(b.name,"pt-BR"));return Response.json({configured:Boolean(config.appId&&config.appSecret),configIdConfigured:Boolean(config.configId),accounts})}catch(error){console.error("Meta accounts GET",error);return Response.json({error:"O banco Neon ainda não respondeu. Confira DATABASE_URL na Vercel."},{status:503})}}
export async function POST(request:Request){try{const userId=await requestUserId(request);if(!userId)return Response.json({error:"Não autenticado."},{status:401});if(!(await hasActivePlan(userId)))return planRequiredResponse();await ensureDb();const body=await request.json().catch(()=>({})) as {accountId?:string;enabled?:boolean};if(!body.accountId)return Response.json({error:"Escolha uma conta."},{status:400});const db=getDb();const[exists]=await db.select({id:metaAccounts.id,adAccountId:metaAccounts.adAccountId}).from(metaAccounts).where(and(eq(metaAccounts.id,body.accountId),eq(metaAccounts.userId,userId))).limit(1);if(!exists)return Response.json({error:"Conta não encontrada."},{status:404});const links=await db.select({adAccountId:metaLinked.adAccountId}).from(metaLinked).where(eq(metaLinked.userId,userId));const isLinked=links.some(l=>l.adAccountId===exists.adAccountId);const enabled=typeof body.enabled==="boolean"?body.enabled:!isLinked;if(enabled){await db.insert(metaLinked).values({userId,adAccountId:exists.adAccountId,createdAt:Math.floor(Date.now()/1000)}).onConflictDoNothing();}else{await db.delete(metaLinked).where(and(eq(metaLinked.userId,userId),eq(metaLinked.adAccountId,exists.adAccountId)));}return Response.json({ok:true,enabled})}catch(error){console.error("Meta accounts POST",error);return Response.json({error:"O banco Neon ainda não respondeu. Confira DATABASE_URL na Vercel."},{status:503})}}
export async function DELETE(request:Request){try{const userId=await requestUserId(request);if(!userId)return Response.json({error:"Não autenticado."},{status:401});if(!(await hasActivePlan(userId)))return planRequiredResponse();await ensureDb();const id=new URL(request.url).searchParams.get("id");if(!id)return Response.json({error:"Conta não informada."},{status:400});const result=await getDb().delete(metaAccounts).where(and(eq(metaAccounts.id,id),eq(metaAccounts.userId,userId))).returning({id:metaAccounts.id});if(!result.length)return Response.json({error:"Conta não encontrada."},{status:404});return Response.json({deleted:true,id})}catch(error){console.error("Meta accounts DELETE",error);return Response.json({error:"Não foi possível remover a conta."},{status:500})}}
