import { and,asc,desc,eq } from "drizzle-orm";
import { ensureDb,getDb } from "@/db";
import { metaAccounts } from "@/db/schema";
import { metaConfig } from "@/lib/meta";
import { requestUserId } from "@/lib/trackbase-security";
export const dynamic="force-dynamic";
export async function GET(request:Request){try{const userId=await requestUserId(request);if(!userId)return Response.json({error:"Não autenticado."},{status:401});await ensureDb();const rows=await getDb().select({id:metaAccounts.id,adAccountId:metaAccounts.adAccountId,name:metaAccounts.accountName,metaUserName:metaAccounts.metaUserName,currency:metaAccounts.currency,timezoneName:metaAccounts.timezoneName,accountStatus:metaAccounts.accountStatus,selected:metaAccounts.selected,tokenExpiresAt:metaAccounts.tokenExpiresAt,connectedAt:metaAccounts.connectedAt}).from(metaAccounts).where(eq(metaAccounts.userId,userId)).orderBy(desc(metaAccounts.selected),asc(metaAccounts.accountName));const config=metaConfig();return Response.json({configured:Boolean(config.appId&&config.appSecret),configIdConfigured:Boolean(config.configId),accounts:rows})}catch(error){console.error("Meta accounts GET",error);return Response.json({error:"O banco Neon ainda não respondeu. Confira DATABASE_URL na Vercel."},{status:503})}}
export async function POST(request:Request){try{const userId=await requestUserId(request);if(!userId)return Response.json({error:"Não autenticado."},{status:401});await ensureDb();const body=await request.json().catch(()=>({})) as {accountId?:string;enabled?:boolean};if(!body.accountId)return Response.json({error:"Escolha uma conta."},{status:400});const db=getDb();const[exists]=await db.select({id:metaAccounts.id,selected:metaAccounts.selected}).from(metaAccounts).where(and(eq(metaAccounts.id,body.accountId),eq(metaAccounts.userId,userId))).limit(1);if(!exists)return Response.json({error:"Conta não encontrada."},{status:404});const enabled=typeof body.enabled==="boolean"?body.enabled:!exists.selected;const updated=await db.update(metaAccounts).set({selected:enabled,updatedAt:Math.floor(Date.now()/1000)}).where(and(eq(metaAccounts.id,body.accountId),eq(metaAccounts.userId,userId))).returning({id:metaAccounts.id,selected:metaAccounts.selected});return Response.json({ok:true,enabled,matched:updated.length})}catch(error){console.error("Meta accounts POST",error);return Response.json({error:"O banco Neon ainda não respondeu. Confira DATABASE_URL na Vercel."},{status:503})}}
export async function DELETE(request:Request){try{const userId=await requestUserId(request);if(!userId)return Response.json({error:"Não autenticado."},{status:401});await ensureDb();const id=new URL(request.url).searchParams.get("id");if(!id)return Response.json({error:"Conta não informada."},{status:400});const result=await getDb().delete(metaAccounts).where(and(eq(metaAccounts.id,id),eq(metaAccounts.userId,userId))).returning({id:metaAccounts.id});if(!result.length)return Response.json({error:"Conta não encontrada."},{status:404});return Response.json({deleted:true,id})}catch(error){console.error("Meta accounts DELETE",error);return Response.json({error:"Não foi possível remover a conta."},{status:500})}}
