"use client";
import {useEffect,useState} from "react";
import {AlertCircle,Loader2,RefreshCw} from "lucide-react";
import {Button} from "@/components/ui/button";

type Row={id:string;name:string;status:string;accountName:string;currency:string;spend:number;clicks:number;impressions:number;cpc:number;cpm:number;pageViews:number;checkouts:number;sales:number;revenue:number;roas:number|null};
const money=(value:number,currency="BRL")=>new Intl.NumberFormat("pt-BR",{style:"currency",currency}).format(value||0);
export function CampaignsClient(){const[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[updated,setUpdated]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const r=await fetch("/api/meta/campaigns",{cache:"no-store"}),b=await r.json();if(!r.ok)throw new Error(b.error||"Falha ao importar campanhas.");setRows(b.campaigns||[]);setUpdated(b.updatedAt||"");if(b.failures?.length)setError(b.failures.map((x:{account:string;error:string})=>`${x.account}: ${x.error}`).join(" · "));}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar.")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-400">{updated?`Atualizado ${new Date(updated).toLocaleString("pt-BR")}`:"Dados da Meta Marketing API"}</p><Button variant="outline" onClick={load} disabled={loading}>{loading?<Loader2 className="animate-spin"/>:<RefreshCw/>}Atualizar campanhas</Button></div>
 {error&&<div className="flex gap-2 rounded-lg border border-amber-500/30 bg-amber-500/10 p-3 text-sm text-amber-200"><AlertCircle className="size-4 shrink-0"/>{error}</div>}
 <div className="metric-card overflow-x-auto rounded-xl"><table className="w-full min-w-[1120px] text-sm"><thead><tr>{["Campanha","Conta","Status","Gasto","Impressões","Cliques","CPC","Acessos","ICs","Vendas","Faturamento","ROAS"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{loading&&!rows.length?<tr><td colSpan={12} className="py-12 text-center text-slate-400"><Loader2 className="mx-auto mb-2 animate-spin"/>Importando da Meta...</td></tr>:rows.length?rows.map(c=><tr key={`${c.accountName}-${c.id}`}><td><b>{c.name}</b><div className="text-xs text-slate-500">{c.id}</div></td><td>{c.accountName}</td><td><span className={c.status==="ACTIVE"?"text-emerald-300":"text-slate-400"}>{c.status==="ACTIVE"?"Ativa":c.status}</span></td><td>{money(c.spend,c.currency)}</td><td>{c.impressions.toLocaleString("pt-BR")}</td><td>{c.clicks.toLocaleString("pt-BR")}</td><td>{money(c.cpc,c.currency)}</td><td>{c.pageViews}</td><td>{c.checkouts}</td><td>{c.sales}</td><td>{money(c.revenue,c.currency)}</td><td>{c.roas==null?"N/A":`${c.roas.toFixed(2)}x`}</td></tr>):<tr><td colSpan={12} className="py-12 text-center text-slate-500">Nenhuma campanha encontrada nas contas vinculadas.</td></tr>}</tbody></table></div></div>}
