"use client";
import {useEffect,useMemo,useState} from "react";
import {AlertCircle,BarChart3,Check,ChevronDown,Clipboard,ExternalLink,Loader2,MoreHorizontal,Pause,Play,RefreshCw,Search,Trash2} from "lucide-react";
import {Button} from "@/components/ui/button";

type Level="account"|"campaign"|"adset"|"ad";
type Row={id:string;name:string;status:string;level:string;accountId:string;adAccountId:string;accountName:string;currency:string;spend:number;clicks:number;impressions:number;cpc:number;cpm:number;pageViews:number;checkouts:number;sales:number;revenue:number;cpa:number|null;profit:number;roas:number|null};
type Daily={date:string;itemName:string;accountName:string;currency:string;spend:number;clicks:number;impressions:number;cpc:number};
const money=(value:number,currency="BRL")=>new Intl.NumberFormat("pt-BR",{style:"currency",currency}).format(value||0),labels:Record<Level,string>={account:"Contas",campaign:"Campanhas",adset:"Conjuntos",ad:"Anúncios"};

export function CampaignsClient(){
 const[rows,setRows]=useState<Row[]>([]),[daily,setDaily]=useState<Daily[]>([]),[level,setLevel]=useState<Level>("campaign"),[period,setPeriod]=useState("last_7d"),[start,setStart]=useState(""),[end,setEnd]=useState(""),[loading,setLoading]=useState(true),[acting,setActing]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[updated,setUpdated]=useState(""),[search,setSearch]=useState(""),[status,setStatus]=useState("all"),[account,setAccount]=useState("all"),[selected,setSelected]=useState<Set<string>>(new Set()),[menu,setMenu]=useState(false),[compare,setCompare]=useState(false);
 const apiLevel=level==="account"?"campaign":level;
 const load=async()=>{setLoading(true);setError("");try{const query=new URLSearchParams({period,level:apiLevel});if(period==="custom"&&start&&end){query.set("start",start);query.set("end",end)}const response=await fetch(`/api/meta/campaigns?${query}`,{cache:"no-store"}),body=await response.json();if(!response.ok)throw new Error(body.error||"Falha ao importar dados.");setRows(body.items||body.campaigns||[]);setDaily(body.daily||[]);setUpdated(body.updatedAt||"");setSelected(new Set());if(body.failures?.length)setError(body.failures.map((item:{account:string;error:string})=>`${item.account}: ${item.error}`).join(" · "))}catch(reason){setError(reason instanceof Error?reason.message:"Falha ao carregar.")}finally{setLoading(false)}};
 useEffect(()=>{load()},[level,period]);
 const accounts=useMemo(()=>Array.from(new Set(rows.map(row=>row.accountName))).sort(),[rows]);
 const displayed=useMemo(()=>{let source=rows;if(level==="account"){const map=new Map<string,Row>();rows.forEach(row=>{const old=map.get(row.accountId);if(old){old.spend+=row.spend;old.clicks+=row.clicks;old.impressions+=row.impressions;old.pageViews+=row.pageViews;old.checkouts+=row.checkouts;old.sales+=row.sales;old.revenue+=row.revenue;old.profit+=row.profit;old.cpa=old.sales?old.spend/old.sales:null;old.roas=old.spend?old.revenue/old.spend:null}else map.set(row.accountId,{...row,id:row.accountId,name:row.accountName,level:"account"})});source=Array.from(map.values())}return source.filter(row=>(!search||`${row.name} ${row.id}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()))&&(status==="all"||row.status===status)&&(account==="all"||row.accountName===account))},[rows,level,search,status,account]);
 const chosen=displayed.filter(row=>selected.has(row.id)),totals=displayed.reduce((sum,row)=>({spend:sum.spend+row.spend,revenue:sum.revenue+row.revenue,sales:sum.sales+row.sales,profit:sum.profit+row.profit}),{spend:0,revenue:0,sales:0,profit:0});
 const act=async(action:"activate"|"pause"|"duplicate"|"budget"|"delete",targets=chosen)=>{if(level==="account"||!targets.length)return;const descriptions={activate:"ativar",pause:"pausar",duplicate:"duplicar",budget:"alterar o orçamento de",delete:"excluir"};if(!confirm(`Deseja ${descriptions[action]} ${targets.length} item(ns)?`))return;let value:number|undefined;if(action==="budget"){const input=prompt("Novo orçamento diário em reais:");if(!input)return;value=Number(input.replace(",","."));if(!value||value<=0)return setError("Informe um orçamento válido.")}setActing(true);setMenu(false);setError("");try{for(const row of targets){const response=await fetch("/api/meta/actions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({accountId:row.accountId,objectId:row.id,level,action,value})}),body=await response.json();if(!response.ok)throw new Error(`${row.name}: ${body.error||"Falha na Meta"}`)}setNotice("Alteração enviada para a Meta com sucesso.");await load()}catch(reason){setError(reason instanceof Error?reason.message:"Não foi possível alterar.")}finally{setActing(false)}};
 const toggle=(id:string)=>setSelected(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next});
 const openManager=()=>{const row=chosen[0]||displayed[0];if(row)window.open(`https://business.facebook.com/adsmanager/manage/${level==="campaign"?"campaigns":level==="adset"?"adsets":"ads"}?act=${row.adAccountId}`,"_blank","noopener")};
 return <div className="space-y-4">
  <div className="grid overflow-hidden rounded-xl border border-white/10 bg-[#101522] sm:grid-cols-4">{(["account","campaign","adset","ad"] as Level[]).map(item=><button key={item} onClick={()=>setLevel(item)} className={`flex items-center justify-center gap-2 px-4 py-4 text-sm font-semibold transition ${level===item?"bg-blue-600/20 text-blue-300 ring-1 ring-inset ring-blue-500/40":"text-slate-400 hover:bg-white/5 hover:text-white"}`}>{item==="account"?"▣":item==="campaign"?"⊞":item==="adset"?"▦":"▤"} {labels[item]}</button>)}</div>
  <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-white/10 bg-[#0e131f] p-3"><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={openManager}><ExternalLink/>Abrir no Gerenciador</Button><Button variant="outline" onClick={()=>setCompare(value=>!value)}><BarChart3/>Comparar</Button><div className="relative"><Button variant="outline" disabled={!chosen.length||level==="account"||acting} onClick={()=>setMenu(value=>!value)}>{acting?<Loader2 className="animate-spin"/>:<MoreHorizontal/>}Ações <ChevronDown/></Button>{menu&&<div className="absolute left-0 z-20 mt-2 w-56 rounded-xl border border-white/10 bg-[#151b29] p-2 shadow-2xl">{[[Play,"Ativar","activate"],[Pause,"Pausar","pause"],[Clipboard,"Duplicar","duplicate"],[BarChart3,"Alterar orçamento","budget"],[Trash2,"Excluir","delete"]].map(([Icon,label,action])=><button key={String(action)} onClick={()=>act(action as "activate"|"pause"|"duplicate"|"budget"|"delete")} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2 text-left text-sm hover:bg-white/5 ${action==="delete"?"text-red-300":"text-slate-300"}`}><Icon className="size-4"/>{String(label)}</button>)}</div>}</div></div><div className="flex items-center gap-3 text-sm text-slate-400"><span>{selected.size} selecionado(s)</span><Button onClick={load} disabled={loading}>{loading?<Loader2 className="animate-spin"/>:<RefreshCw/>}Atualizar</Button></div></div>
  <div className="grid gap-3 rounded-xl border border-white/10 bg-[#0e131f] p-4 md:grid-cols-5"><label className="relative md:col-span-2"><Search className="absolute left-3 top-3 size-4 text-slate-500"/><input className="dashboard-input pl-9" value={search} onChange={event=>setSearch(event.target.value)} placeholder={`Filtrar ${labels[level].toLocaleLowerCase()} por nome ou ID`}/></label><select className="dashboard-input" value={status} onChange={event=>setStatus(event.target.value)}><option value="all">Qualquer status</option><option value="ACTIVE">Ativa</option><option value="PAUSED">Pausada</option></select><select className="dashboard-input" value={account} onChange={event=>setAccount(event.target.value)}><option value="all">Qualquer conta</option>{accounts.map(name=><option key={name}>{name}</option>)}</select><select className="dashboard-input" value={period} onChange={event=>setPeriod(event.target.value)}>{[["today","Hoje"],["yesterday","Ontem"],["last_7d","Últimos 7 dias"],["last_30d","Últimos 30 dias"],["this_month","Este mês"],["last_month","Mês passado"],["maximum","Todo o período"],["custom","Personalizado"]].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>{period==="custom"&&<div className="flex gap-2 md:col-span-5"><input type="date" className="dashboard-input" value={start} onChange={event=>setStart(event.target.value)}/><input type="date" className="dashboard-input" value={end} onChange={event=>setEnd(event.target.value)}/><Button onClick={load}>Aplicar datas</Button></div>}</div>
  {error&&<div className="flex gap-2 rounded-lg border border-amber-500/30 bg-amber-500/10 p-3 text-sm text-amber-200"><AlertCircle className="size-4 shrink-0"/>{error}</div>}{notice&&<div className="flex gap-2 rounded-lg border border-emerald-500/30 bg-emerald-500/10 p-3 text-sm text-emerald-200"><Check className="size-4"/>{notice}</div>}
  {compare&&<div className="grid gap-3 sm:grid-cols-4">{[["Gasto",money(totals.spend)],["Vendas",totals.sales],["Faturamento",money(totals.revenue)],["Lucro",money(totals.profit)]].map(([label,value])=><div key={String(label)} className="metric-card rounded-xl p-4"><p className="text-xs uppercase text-slate-500">{label}</p><strong className="mt-2 block text-xl">{value}</strong></div>)}</div>}
  <div className="metric-card overflow-x-auto rounded-xl"><table className="w-full min-w-[1320px] text-sm"><thead><tr><th><input type="checkbox" checked={displayed.length>0&&selected.size===displayed.length} onChange={event=>setSelected(event.target.checked?new Set(displayed.map(row=>row.id)):new Set())}/></th>{["Status",level==="account"?"Conta":level==="campaign"?"Campanha":level==="adset"?"Conjunto":"Anúncio","Conta de anúncio","Cliques","Acessos","ICs","Vendas","CPA","Gastos","Faturamento","Lucro","ROAS"].map(title=><th key={title}>{title}</th>)}</tr></thead><tbody>{loading&&!displayed.length?<tr><td colSpan={13} className="py-14 text-center text-slate-400"><Loader2 className="mx-auto mb-2 animate-spin"/>Importando da Meta...</td></tr>:displayed.length?displayed.map(row=><tr key={row.id}><td><input type="checkbox" checked={selected.has(row.id)} onChange={()=>toggle(row.id)}/></td><td><button disabled={level==="account"||acting} onClick={()=>act(row.status==="ACTIVE"?"pause":"activate",[row])} className={`h-6 w-11 rounded-full p-1 transition ${row.status==="ACTIVE"?"bg-blue-600":"bg-slate-600"}`}><span className={`block size-4 rounded-full bg-white transition ${row.status==="ACTIVE"?"translate-x-5":""}`}/></button></td><td><b>{row.name}</b><div className="text-xs text-slate-500">{row.id}</div></td><td>{row.accountName}</td><td>{row.clicks.toLocaleString("pt-BR")}</td><td>{row.pageViews}</td><td>{row.checkouts}</td><td>{row.sales}</td><td>{row.cpa==null?"N/A":money(row.cpa,row.currency)}</td><td>{money(row.spend,row.currency)}</td><td>{money(row.revenue,row.currency)}</td><td className={row.profit>=0?"text-emerald-300":"text-red-300"}>{money(row.profit,row.currency)}</td><td>{row.roas==null?"N/A":`${row.roas.toFixed(2)}x`}</td></tr>):<tr><td colSpan={13} className="py-14 text-center text-slate-500">Nenhum item encontrado nesse período.</td></tr>}</tbody></table></div>
  <div className="flex flex-wrap justify-between gap-2 text-xs text-slate-500"><span>{displayed.length} item(ns) · {updated?`Atualizado ${new Date(updated).toLocaleString("pt-BR")}`:"aguardando atualização"}</span><span>Gasto por dia: {daily.length} registro(s)</span></div>
 </div>
}
