import { index, integer, sqliteTable, real, text, uniqueIndex } from "drizzle-orm/sqlite-core";
export const workspaces=sqliteTable("workspaces",{id:text("id").primaryKey(),name:text("name").notNull(),createdAt:text("created_at").notNull()});
export const members=sqliteTable("members",{id:text("id").primaryKey(),workspaceId:text("workspace_id").notNull(),userId:text("user_id").notNull(),email:text("email"),role:text("role").notNull().default("member")},t=>[uniqueIndex("idx_members_workspace_user").on(t.workspaceId,t.userId)]);
export const projects=sqliteTable("projects",{id:text("id").primaryKey(),workspaceId:text("workspace_id").notNull(),name:text("name").notNull(),domain:text("domain"),publicKey:text("public_key"),webhookSecretHash:text("webhook_secret_hash"),pixelId:text("pixel_id"),metaTokenCipher:text("meta_token_cipher"),metaTokenIv:text("meta_token_iv"),metaTestCode:text("meta_test_code"),metaConnectedAt:text("meta_connected_at"),trackingConfig:text("tracking_config"),createdAt:text("created_at").notNull()},t=>[index("idx_projects_workspace").on(t.workspaceId),uniqueIndex("idx_projects_public_key").on(t.publicKey)]);
export const events=sqliteTable("events",{id:text("id").primaryKey(),projectId:text("project_id").notNull(),eventId:text("event_id").notNull(),eventName:text("event_name").notNull(),source:text("source").notNull(),occurredAt:integer("occurred_at").notNull(),visitorId:text("visitor_id"),fbclid:text("fbclid"),fbp:text("fbp"),fbc:text("fbc"),utmSource:text("utm_source"),utmCampaign:text("utm_campaign"),utmMedium:text("utm_medium"),utmContent:text("utm_content"),utmTerm:text("utm_term"),value:real("value"),currency:text("currency"),payload:text("payload")},t=>[uniqueIndex("idx_events_project_event").on(t.projectId,t.eventId),index("idx_events_project_time").on(t.projectId,t.occurredAt),index("idx_events_project_name_time").on(t.projectId,t.eventName,t.occurredAt)]);
export const orders=sqliteTable("orders",{id:text("id").primaryKey(),projectId:text("project_id").notNull(),externalId:text("external_id").notNull(),provider:text("provider").notNull(),status:text("status").notNull(),value:real("value").notNull(),currency:text("currency").notNull(),utmCampaign:text("utm_campaign"),utmSource:text("utm_source"),utmMedium:text("utm_medium"),utmContent:text("utm_content"),utmTerm:text("utm_term"),eventId:text("event_id"),createdAt:integer("created_at").notNull(),updatedAt:integer("updated_at").notNull()},t=>[uniqueIndex("idx_orders_provider_external").on(t.provider,t.externalId),index("idx_orders_project_time").on(t.projectId,t.createdAt)]);
export const apiCredentials=sqliteTable("api_credentials",{id:text("id").primaryKey(),workspaceId:text("workspace_id").notNull(),projectId:text("project_id").notNull(),name:text("name").notNull(),provider:text("provider").notNull().default("generic"),tokenHash:text("token_hash").notNull(),active:integer("active").notNull().default(1),createdAt:text("created_at").notNull(),lastUsedAt:text("last_used_at")},t=>[uniqueIndex("idx_api_credentials_token").on(t.tokenHash),index("idx_api_credentials_workspace").on(t.workspaceId),index("idx_api_credentials_project").on(t.projectId)]);
export const metaOauthStates=sqliteTable("meta_oauth_states",{id:text("id").primaryKey(),userId:text("user_id").notNull(),stateHash:text("state_hash").notNull(),expiresAt:integer("expires_at").notNull(),createdAt:integer("created_at").notNull()},t=>[uniqueIndex("idx_meta_oauth_states_hash").on(t.stateHash),index("idx_meta_oauth_states_user").on(t.userId)]);
export const users=sqliteTable("users",{id:text("id").primaryKey(),email:text("email").notNull().unique(),passwordHash:text("password_hash").notNull(),name:text("name"),cpf:text("cpf").unique(),createdAt:integer("created_at").notNull(),role:text("role").notNull().default("member"),totpSecretCipher:text("totp_secret_cipher"),totpIv:text("totp_iv"),totpEnabled:integer("totp_enabled").notNull().default(0),emailVerifiedAt:integer("email_verified_at"),failedAttempts:integer("failed_attempts").notNull().default(0),lockedUntil:integer("locked_until")});
export const sessions=sqliteTable("sessions",{id:text("id").primaryKey(),userId:text("user_id").notNull(),tokenHash:text("token_hash").notNull().unique(),isAdmin:integer("is_admin").notNull().default(0),pending2fa:integer("pending_2fa").notNull().default(0),expiresAt:integer("expires_at").notNull(),createdAt:integer("created_at").notNull(),lastSeenAt:integer("last_seen_at").notNull(),ip:text("ip"),userAgent:text("user_agent")},t=>[index("idx_sessions_user").on(t.userId),index("idx_sessions_expires").on(t.expiresAt)]);
export const loginAttempts=sqliteTable("login_attempts",{id:text("id").primaryKey(),email:text("email"),ip:text("ip"),success:integer("success").notNull().default(0),createdAt:integer("created_at").notNull()},t=>[index("idx_login_attempts_email_time").on(t.email,t.createdAt),index("idx_login_attempts_ip_time").on(t.ip,t.createdAt)]);
export const passwordResets=sqliteTable("password_resets",{id:text("id").primaryKey(),userId:text("user_id").notNull(),tokenHash:text("token_hash").notNull().unique(),expiresAt:integer("expires_at").notNull(),usedAt:integer("used_at"),createdAt:integer("created_at").notNull()},t=>[index("idx_password_resets_user").on(t.userId)]);
export const emailVerifications=sqliteTable("email_verifications",{id:text("id").primaryKey(),userId:text("user_id").notNull(),tokenHash:text("token_hash").notNull().unique(),expiresAt:integer("expires_at").notNull(),usedAt:integer("used_at"),createdAt:integer("created_at").notNull()},t=>[index("idx_email_verifications_user").on(t.userId)]);
// Códigos numéricos de 6 dígitos (recuperação de senha e confirmação de
// e-mail). O código em claro nunca é persistido — só o hash SHA-256.
// `attempts` limita força bruta por código; `purpose` separa os fluxos.
export const verificationCodes=sqliteTable("verification_codes",{id:text("id").primaryKey(),userId:text("user_id").notNull(),email:text("email").notNull(),purpose:text("purpose").notNull(),codeHash:text("code_hash").notNull(),expiresAt:integer("expires_at").notNull(),attempts:integer("attempts").notNull().default(0),usedAt:integer("used_at"),createdAt:integer("created_at").notNull()},t=>[index("idx_verification_codes_email_purpose").on(t.email,t.purpose,t.createdAt),index("idx_verification_codes_user").on(t.userId)]);
// Outbox do CAPI (Meta Conversions API): o webhook responde rápido e o envio
// à Meta é garantido por retries. `payload` = corpo do evento SEM o token
// (o token é relido do projeto na hora do dreno). status: pending|processing|
// dead (dead = DLQ, após ~24h de backoff + alerta push).
export const capiOutbox=sqliteTable("capi_outbox",{id:text("id").primaryKey(),workspaceId:text("workspace_id").notNull(),projectId:text("project_id").notNull(),pixelId:text("pixel_id").notNull(),eventName:text("event_name").notNull(),eventId:text("event_id").notNull(),payload:text("payload").notNull(),status:text("status").notNull().default("pending"),attempts:integer("attempts").notNull().default(0),nextAttemptAt:integer("next_attempt_at").notNull(),lastError:text("last_error"),createdAt:integer("created_at").notNull(),updatedAt:integer("updated_at").notNull()},t=>[index("idx_capi_outbox_due").on(t.status,t.nextAttemptAt),index("idx_capi_outbox_project").on(t.projectId)]);
export const googleOauthStates=sqliteTable("google_oauth_states",{id:text("id").primaryKey(),userId:text("user_id").notNull(),stateHash:text("state_hash").notNull(),expiresAt:integer("expires_at").notNull(),createdAt:integer("created_at").notNull()},t=>[uniqueIndex("idx_google_oauth_states_hash").on(t.stateHash),index("idx_google_oauth_states_user").on(t.userId)]);
export const metaLinked=sqliteTable("meta_linked",{userId:text("user_id").notNull(),adAccountId:text("ad_account_id").notNull(),createdAt:integer("created_at").notNull()},t=>[uniqueIndex("idx_meta_linked_user_ad").on(t.userId,t.adAccountId)]);
export const pushSubscriptions=sqliteTable("push_subscriptions",{workspaceId:text("workspace_id").notNull(),endpoint:text("endpoint").notNull(),p256dh:text("p256dh").notNull(),auth:text("auth").notNull(),createdAt:integer("created_at").notNull()},t=>[uniqueIndex("idx_push_sub_endpoint").on(t.workspaceId,t.endpoint)]);
export const notificationPrefs=sqliteTable("notification_prefs",{workspaceId:text("workspace_id").primaryKey(),userId:text("user_id"),prefs:text("prefs").notNull(),updatedAt:integer("updated_at").notNull()});
export const soundPrefs=sqliteTable("sound_prefs",{workspaceId:text("workspace_id").primaryKey(),userId:text("user_id"),prefs:text("prefs").notNull(),updatedAt:integer("updated_at").notNull()});
export const automationRules=sqliteTable("automation_rules",{id:text("id").primaryKey(),workspaceId:text("workspace_id").notNull(),userId:text("user_id").notNull(),name:text("name").notNull(),level:text("level").notNull(),metric:text("metric").notNull(),operator:text("operator").notNull(),value:real("value").notNull(),windowDays:integer("window_days").notNull(),minSpend:real("min_spend").notNull(),action:text("action").notNull(),active:integer("active").notNull(),cooldownHours:integer("cooldown_hours").notNull(),lastTriggeredAt:integer("last_triggered_at"),createdAt:integer("created_at").notNull(),updatedAt:integer("updated_at").notNull()});
export const actionHistory=sqliteTable("action_history",{id:text("id").primaryKey(),workspaceId:text("workspace_id").notNull(),userId:text("user_id").notNull(),ruleId:text("rule_id"),actor:text("actor").notNull(),action:text("action").notNull(),targetLevel:text("target_level"),targetId:text("target_id"),targetName:text("target_name"),detail:text("detail"),createdAt:integer("created_at").notNull()},t=>[index("idx_action_history_ws").on(t.workspaceId,t.createdAt)]);
export const metaAccounts=sqliteTable("meta_accounts",{id:text("id").primaryKey(),workspaceId:text("workspace_id").notNull(),userId:text("user_id").notNull(),metaUserId:text("meta_user_id"),metaUserName:text("meta_user_name"),adAccountId:text("ad_account_id").notNull(),accountName:text("account_name").notNull(),currency:text("currency"),timezoneName:text("timezone_name"),accountStatus:integer("account_status"),accessTokenCipher:text("access_token_cipher").notNull(),accessTokenIv:text("access_token_iv").notNull(),tokenExpiresAt:integer("token_expires_at"),selected:integer("selected").notNull().default(0),connectedAt:integer("connected_at").notNull(),updatedAt:integer("updated_at").notNull()},t=>[uniqueIndex("idx_meta_accounts_user_ad").on(t.userId,t.adAccountId),index("idx_meta_accounts_workspace").on(t.workspaceId),index("idx_meta_accounts_selected").on(t.userId,t.selected)]);
export const planSubscriptions=sqliteTable("plan_subscriptions",{id:text("id").primaryKey(),workspaceId:text("workspace_id").notNull(),userId:text("user_id").notNull(),email:text("email"),plan:text("plan").notNull(),planVersion:integer("plan_version"),status:text("status").notNull(),caktoOrderId:text("cakto_order_id"),caktoSubscriptionId:text("cakto_subscription_id"),caktoOfferId:text("cakto_offer_id"),amount:text("amount"),currency:text("currency"),currentPeriodStart:integer("current_period_start"),currentPeriodEnd:integer("current_period_end"),cancelAtPeriodEnd:integer("cancel_at_period_end"),excessEnabled:integer("excess_enabled").notNull().default(0),excessCap:integer("excess_cap"),scheduledPlan:text("scheduled_plan"),scheduledAt:integer("scheduled_at"),createdAt:integer("created_at").notNull(),updatedAt:integer("updated_at").notNull()},t=>[index("idx_plan_subs_workspace").on(t.workspaceId),uniqueIndex("idx_plan_subs_cakto_sub").on(t.caktoSubscriptionId),index("idx_plan_subs_email").on(t.email)]);
export const webhookEvents=sqliteTable("webhook_events",{id:text("id").primaryKey(),provider:text("provider").notNull(),eventId:text("event_id").notNull(),eventType:text("event_type").notNull(),payload:text("payload").notNull(),status:text("status").notNull().default("received"),createdAt:integer("created_at").notNull(),processedAt:integer("processed_at")},t=>[uniqueIndex("idx_webhook_events_provider_event").on(t.provider,t.eventId),index("idx_webhook_events_type").on(t.eventType)]);
export const usageCounters=sqliteTable("usage_counters",{id:text("id").primaryKey(),workspaceId:text("workspace_id").notNull(),metric:text("metric").notNull(),periodStart:integer("period_start").notNull(),periodEnd:integer("period_end").notNull(),count:integer("count").notNull().default(0),updatedAt:integer("updated_at").notNull()},t=>[uniqueIndex("idx_usage_ws_metric_period").on(t.workspaceId,t.metric,t.periodStart)]);
export const auditLogs=sqliteTable("audit_logs",{id:text("id").primaryKey(),workspaceId:text("workspace_id"),userId:text("user_id"),action:text("action").notNull(),targetType:text("target_type"),targetId:text("target_id"),detail:text("detail"),ip:text("ip"),createdAt:integer("created_at").notNull()},t=>[index("idx_audit_ws_time").on(t.workspaceId,t.createdAt),index("idx_audit_user").on(t.userId)]);