"use client";
import { useCallback,useEffect,useState } from "react";
import { Button } from "@/components/ui/button";
import { Check,CheckCircle2,Copy,ExternalLink,Info,KeyRound,Loader2,RefreshCw,Trash2 } from "lucide-react";
import { copyText } from "@/lib/clipboard";

type Account={id:string;adAccountId:string;name:string;metaUserId?:string;metaUserName?:string;currency?:string;timezoneName?:string;accountStatus?:number;selected:boolean;tokenExpiresAt?:number};
async function readJson(r:Response){const text=await r.text();if(!text)throw new Error(`A API não respondeu (${r.status}).`);try{return JSON.parse(text)}catch{throw new Error(`Resposta inválida da API (${r.status}).`)}}

export function MetaAccountsClient(){
 const [data,setData]=useState<{configured:boolean;configIdConfigured:boolean;callbackUrl?:string;appIdSuffix?:string;accounts:Account[]}|null>(null);const [error,setError]=useState("");const [saving,setSaving]=useState("");const [copied,setCopied]=useState(false);const [manual,setManual]=useState(false);const [token,setToken]=useState("");const [sending,setSending]=useState(false);const [okMsg,setOkMsg]=useState("");const [now,setNow]=useState(0);
 const load=useCallback(async()=>{setError("");const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetch("/api/meta/accounts",{signal:controller.signal,cache:"no-store",credentials:"same-origin"});const b=await readJson(r);if(r.status===401){window.location.assign(`/login?return_to=${encodeURIComponent("/contas-meta")}`);return;}if(!r.ok)throw new Error(b.error||"Falha ao carregar contas.");setData(b);}catch(e){setError(e instanceof DOMException&&e.name==="AbortError"?"A lista de contas demorou para responder. Tente novamente sem sair desta página.":e instanceof Error?e.message:"Não foi possível carregar.");}finally{clearTimeout(timer)}},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>{void load();},0);return()=>window.clearTimeout(timer)},[load]);
 useEffect(()=>{const frame=window.requestAnimationFrame(()=>{const p=new URLSearchParams(window.location.search);const messages:Record<string,string>={cancelado:"Autorização cancelada. Você pode tentar novamente.",sessao:"A conexão expirou ou já foi utilizada. Inicie novamente.",sem_contas:"A Meta não retornou contas de anúncios acessíveis.",oauth:"Não foi possível concluir a conexão. Tente novamente.",config:"A conexão Meta ainda não está configurada.",start:"Não foi possível iniciar a conexão.",retorno:"Retorno de autorização incompleto."};if(p.get("erro"))setOkMsg(messages[p.get("erro")!]||"Não foi possível conectar.");else if(p.get("conectado")==="1")setOkMsg("Conexão concluída. Selecione as contas abaixo.");if(p.has("erro")||p.has("conectado")){p.delete("erro");p.delete("conectado");p.delete("contas");const query=p.toString();window.history.replaceState(null,"",window.location.pathname+(query?`?${query}`:"")+window.location.hash)}setNow(Date.now())});return()=>window.cancelAnimationFrame(frame)},[]);
 const select=async(account:Account)=>{setSaving(account.id);setError("");try{const r=await fetch("/api/meta/accounts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({accountId:account.id,enabled:!account.selected}),cache:"no-store"});const b=await readJson(r);if(r.status===402){setOkMsg("Vincular contas e importar campanhas exige um plano ativo. Abra Ver planos para liberar o recurso.");return;}if(!r.ok)throw new Error(b.error||"Falha ao vincular a conta.");setOkMsg(account.selected?"Conta desvinculada.":"Conta vinculada. Acesse Campanhas para importar os dados.");await load();}catch(e){setError(e instanceof Error?e.message:"Falha ao vincular a conta.");}finally{setSaving("");}};
  const accounts=data?.accounts||[];const configured=data?.configured!==false;
  const [link,setLink]=useState<{url:string;expiresAt:number}|null>(null);const [linkBusy,setLinkBusy]=useState(false);
  // Link de conexão para multilogin (AdsPower): abre o Facebook direto, sem
  // login nem cookie da GhostScale no perfil. Vale 24 h; gerar outro cancela o anterior.
  const makeLink=async()=>{setLinkBusy(true);setError("");try{const r=await fetch("/api/meta/connect-link",{method:"POST",cache:"no-store",credentials:"same-origin"});const b=await readJson(r);if(r.status===401){window.location.assign(`/login?return_to=${encodeURIComponent("/contas-meta")}`);return;}if(!r.ok)throw new Error(b.error||"Não foi possível gerar o link.");setLink(b);if(await copyText(b.url)){setCopied(true);setTimeout(()=>setCopied(false),1800)}}catch(e){setError(e instanceof Error?e.message:"Não foi possível gerar o link.")}finally{setLinkBusy(false)}};
  const copyLink=async()=>{if(!link)return makeLink();setError("");if(await copyText(link.url)){setCopied(true);setTimeout(()=>setCopied(false),1800)}else{setError("Não foi possível copiar. Selecione o link abaixo e copie manualmente.")}};
 const removeLogin=async(login:{id:string;name:string;count:number})=>{if(!window.confirm(`Desconectar o login Meta “${login.name}”? As ${login.count} conta(s) de anúncios dele saem da GhostScale e a autorização do app na Meta é revogada.`))return;setSaving(`login:${login.id}`);setError("");setOkMsg("");const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),20000);try{const response=await fetch("/api/meta/accounts?loginId="+encodeURIComponent(login.id),{method:"DELETE",credentials:"same-origin",cache:"no-store",signal:controller.signal});if(response.status===401){window.location.assign(`/login?return_to=${encodeURIComponent("/contas-meta")}`);return;}const body=await readJson(response);if(!response.ok)throw new Error(body.error||"Não foi possível remover o login Meta.");setOkMsg(`Login Meta desconectado. ${body.accountsRemoved||login.count} conta(s) removida(s).${body.revoked?" A autorização na Meta também foi revogada.":""} Para entrar com outro perfil, saia do Facebook neste navegador antes de conectar de novo.`);await load()}catch(e){setError(e instanceof DOMException&&e.name==="AbortError"?"A desconexão demorou para responder. Atualize a página para conferir.":e instanceof Error?e.message:"Não foi possível remover o login Meta.")}finally{clearTimeout(timer);setSaving("")}};
 const connectManual=async()=>{setSending(true);setError("");setOkMsg("");try{const r=await fetch("/api/meta/manual-token",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({accessToken:token}),cache:"no-store"});const b=await readJson(r);if(r.status===402){setOkMsg("Conectar uma conta Meta exige um plano ativo. Abra Ver planos para liberar o recurso.");return;}if(!r.ok)throw new Error(b.error||"Falha ao conectar.");setToken("");const until=b.validUntil?new Date(b.validUntil*1000).toLocaleDateString("pt-BR"):null;setOkMsg(`Conectado como ${b.metaUser||"usuário Meta"} com ${b.accounts} conta(s).${until?` Token válido até ${until}.`:""} Vincule abaixo.`);await load();}catch(e){setError(e instanceof Error?e.message:"Falha ao conectar.")}finally{setSending(false)}};
 // Contas antigas sem meta_user_id viram um grupo próprio ("sem-login") para
 // também poderem ser desconectadas.
 const logins=Array.from(accounts.reduce((map,account)=>{const id=account.metaUserId||"sem-login";const current=map.get(id);map.set(id,{id,name:current?.name||(account.metaUserId?account.metaUserName||"Conta Meta":"Contas sem login identificado"),count:(current?.count||0)+1});return map},new Map<string,{id:string;name:string;count:number}>()).values());
 return <div className="min-w-0 space-y-5">
   {data&&!configured&&<div role="alert" className="rounded-lg border border-amber-400/25 bg-amber-400/10 p-4"><h3 className="font-medium text-amber-700">Aplicativo Meta precisa das credenciais</h3><p className="mt-2 text-sm leading-6 text-slate-500">Configure META_APP_ID e META_APP_SECRET no ambiente do servidor. META_LOGIN_CONFIG_ID é usado pelo Facebook Login for Business.</p></div>}
   {error&&<p role="alert" className="rounded-lg border border-red-400/25 bg-red-400/10 p-3 text-sm text-red-600">{error}</p>}
   <div className="grid gap-2 sm:grid-cols-2 xl:flex xl:flex-wrap">
    <Button asChild={configured} disabled={!configured} className="h-11 w-full px-4 sm:col-span-2 xl:w-auto">{configured?<a href="/api/meta/oauth/start" target="_top" rel="noreferrer"><ExternalLink/>{accounts.length?"Conectar outra conta Meta":"Continuar com Facebook"}</a>:<span><ExternalLink/>Conexão indisponível</span>}</Button>
    <Button variant="outline" className="h-11 w-full px-3 xl:w-auto" onClick={()=>setManual(v=>!v)}><KeyRound/>{manual?"Fechar token manual":"Usar token manual"}</Button>
    {accounts.length>0&&<Button variant="outline" className="h-11 w-full px-3 xl:w-auto" onClick={load}><RefreshCw/>Atualizar contas</Button>}
   </div>
   <section className="rounded-xl border border-border bg-card p-4 sm:p-5"><h3 className="font-semibold">Multilogin (AdsPower)</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Gere o link, cole na barra de endereço do perfil do AdsPower e entre no Facebook desse perfil. A conta conecta direto aqui, <b className="text-foreground">sem login da GhostScale e sem cookie</b> no perfil.</p><div className="mt-3 flex flex-col gap-2 sm:flex-row"><Button type="button" className="min-h-11 w-full sm:w-auto" disabled={linkBusy||!configured} onClick={link?copyLink:makeLink}>{linkBusy?<Loader2 className="animate-spin"/>:copied?<Check/>:<Copy/>}{copied?"Link copiado":link?"Copiar link":"Gerar link de conexão"}</Button>{link&&<Button type="button" variant="outline" className="min-h-11 w-full sm:w-auto" disabled={linkBusy} onClick={makeLink}><RefreshCw/>Gerar novo</Button>}</div>{link&&<><p className="mt-3 select-all break-all rounded-lg bg-muted/50 p-3 font-mono text-xs text-muted-foreground">{link.url}</p><p className="mt-2 text-xs text-muted-foreground">Vale até {new Date(link.expiresAt*1000).toLocaleString("pt-BR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"})} e pode ser usado em vários perfis. Gerar um novo cancela este. Não compartilhe: quem tiver o link conecta contas na sua GhostScale.</p></>}</section>
   {logins.length>0&&<section className="rounded-xl border border-border bg-card p-4 sm:p-5"><h3 className="font-semibold">Logins Meta conectados</h3><p className="mt-1 text-sm text-muted-foreground">Remover um login apaga da GhostScale todas as BMs e contas de anúncios trazidas por ele.</p><div className="mt-4 space-y-2">{logins.map(login=><div key={login.id} className="flex flex-col gap-3 rounded-xl border border-border p-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><strong className="break-words">{login.name}</strong><p className="text-xs text-muted-foreground">{login.count} conta(s) de anúncios conectada(s)</p></div><Button type="button" variant="outline" className="h-11 w-full text-red-600 sm:w-auto" disabled={Boolean(saving)} onClick={()=>removeLogin(login)}>{saving===`login:${login.id}`?<Loader2 className="animate-spin"/>:<Trash2/>}Desconectar login</Button></div>)}</div></section>}
   {data?.callbackUrl&&<details className="group rounded-xl border border-slate-200 bg-slate-50"><summary className="flex min-h-11 cursor-pointer list-none items-center gap-2 px-3 text-sm font-medium text-slate-600"><Info className="size-4 shrink-0"/>Detalhes técnicos da conexão</summary><p className="break-all border-t border-slate-200 px-3 py-3 text-xs leading-5 text-slate-500">Callback cadastrado na Meta: <b className="text-foreground">{data.callbackUrl}</b>{data.appIdSuffix?` · App termina em ${data.appIdSuffix}`:""}</p></details>}
   {okMsg&&<p role="status" className="rounded-lg border border-emerald-400/25 bg-emerald-400/10 p-3 text-sm text-emerald-700">{okMsg}</p>}
   {manual&&<div className="space-y-4 rounded-xl border border-slate-200 bg-slate-50 p-4 sm:p-5"><div><h3 className="font-semibold">Conectar com token manual</h3><p className="mt-1 text-sm leading-6 text-slate-500">Use esta opção somente se o login normal da Meta não estiver disponível.</p></div><ol className="list-decimal space-y-1.5 pl-5 text-sm leading-6 text-slate-500"><li>Abra <a className="font-medium text-blue-600 underline" href="https://developers.facebook.com/tools/explorer" target="_blank" rel="noreferrer">a ferramenta da Meta</a> na conta dona do aplicativo.</li><li>Escolha o aplicativo e permita <b>ads_read</b> e <b>ads_management</b>.</li><li>Gere o token e cole no campo abaixo.</li></ol><div className="flex flex-col gap-2 sm:flex-row"><input className="dashboard-input min-h-11 min-w-0 flex-1" value={token} onChange={e=>setToken(e.target.value)} placeholder="Cole o token da Meta" type="password" aria-label="Token de acesso Meta" autoComplete="off" spellCheck={false}/><Button className="h-11 w-full sm:w-auto" disabled={sending||!token.trim()} onClick={connectManual}>{sending?<Loader2 className="animate-spin"/>:<KeyRound/>}{sending?"Validando...":"Validar e conectar"}</Button></div></div>}
   {!data&&!error&&<div role="status" className="flex min-h-24 items-center justify-center gap-3 rounded-xl border border-slate-200 bg-slate-50 px-4 text-sm text-slate-500"><Loader2 className="size-5 animate-spin"/><span>Buscando contas conectadas…</span></div>}
   {data&&accounts.length===0?<div className="rounded-xl border border-dashed border-slate-200 bg-slate-50 p-5 sm:p-6"><h3 className="font-semibold text-foreground">Nenhuma conta conectada</h3><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Toque em <b className="text-foreground">Continuar com Facebook</b> para autorizar a conta. Depois disso, suas contas de anúncio aparecerão aqui para vinculação.</p></div>:<div className="grid gap-3">{accounts.map(a=><div key={a.id} className={`flex min-w-0 flex-col gap-4 rounded-xl border p-4 sm:flex-row sm:items-center sm:justify-between ${a.selected?"border-violet-400/60 bg-violet-500/10":"border-slate-200"}`}><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><strong className="break-words">{a.name}</strong>{a.selected&&<span className="inline-flex items-center gap-1 text-sm text-emerald-700"><CheckCircle2 className="size-4"/>Vinculada</span>}</div>{a.metaUserName&&<p className="mt-1 break-words text-sm text-blue-600">Login Meta: {a.metaUserName}</p>}<p className="mt-1 break-words text-sm leading-6 text-slate-500">act_{a.adAccountId}<span className="mx-1.5">·</span>{a.currency||"Moeda não informada"}<span className="mx-1.5">·</span>{a.timezoneName||"Fuso não informado"}</p>{a.tokenExpiresAt!=null&&(a.tokenExpiresAt*1000>now?<p className="mt-1 text-xs text-slate-500">Token válido até {new Date(a.tokenExpiresAt*1000).toLocaleDateString("pt-BR")}</p>:<p className="mt-1 text-xs font-medium text-red-600">Token expirado — conecte este login novamente</p>)}</div><Button className="h-11 w-full sm:w-auto" variant={a.selected?"outline":"default"} disabled={Boolean(saving)} onClick={()=>select(a)}>{saving===a.id?<Loader2 className="animate-spin"/>:null}{a.selected?"Desvincular BM":"Vincular BM"}</Button></div>)}</div>}
 </div>;
}
