import {and,gte,inArray,lte,eq} from "drizzle-orm";
import {ensureDb,getDb} from "@/db";
import {events,projects} from "@/db/schema";
import {requestUserId,sha256} from "@/lib/trackbase-security";

type Payload=Record<string,unknown>;
function nested(source:Payload,paths:string[]){for(const path of paths){let value:unknown=source;for(const key of path.split("."))value=value&&typeof value==="object"?(value as Payload)[key]:undefined;if(value!==undefined&&value!==null&&value!=="")return value}}
function payload(value:string|null){try{return JSON.parse(value||"{}") as Payload}catch{return {}}}
function range(params:URLSearchParams){const now=new Date(),end=Math.floor(Date.now()/1000);let start=0;const period=params.get("period")||"last_7d";const day=(d:Date)=>Math.floor(new Date(d.getFullYear(),d.getMonth(),d.getDate()).getTime()/1000);if(period==="today")start=day(now);else if(period==="yesterday"){const d=new Date(now);d.setDate(d.getDate()-1);start=day(d);return {start,end:start+86399,period}}else if(period==="last_7d")start=end-7*86400;else if(period==="last_30d")start=end-30*86400;else if(period==="this_month")start=Math.floor(new Date(now.getFullYear(),now.getMonth(),1).getTime()/1000);else if(period==="last_month"){const a=new Date(now.getFullYear(),now.getMonth()-1,1),b=new Date(now.getFullYear(),now.getMonth(),1);return {start:Math.floor(a.getTime()/1000),end:Math.floor(b.getTime()/1000)-1,period}}else if(period==="custom"){const a=params.get("start"),b=params.get("end");start=a?Math.floor(new Date(a+"T00:00:00").getTime()/1000):end-7*86400;return {start,end:b?Math.floor(new Date(b+"T23:59:59").getTime()/1000):end,period}}return {start,end,period}}
export async function GET(request:Request){try{const userId=await requestUserId(request);if(!userId)return Response.json({error:"Não autenticado."},{status:401});await ensureDb();const db=getDb(),workspaceId="ws_"+(await sha256(userId)).slice(0,24),params=new URL(request.url).searchParams,r=range(params);const ps=await db.select({id:projects.id,name:projects.name}).from(projects).where(eq(projects.workspaceId,workspaceId));if(!ps.length)return Response.json({metrics:{},daily:[],hourly:[],products:[],sources:[],payments:[],countries:[],filters:{products:[],sources:[]},period:r});const rows=await db.select().from(events).where(and(inArray(events.projectId,ps.map(p=>p.id)),gte(events.occurredAt,r.start),lte(events.occurredAt,r.end)));const enriched=rows.map(e=>{const p=payload(e.payload),product=String(nested(p,["product_name","product.name","data.product.name","contentName","custom_data.content_name"])||"Sem produto"),payment=String(nested(p,["payment_method","paymentMethod","data.payment_method","data.payment.method"])||"Não informado").toLowerCase(),country=String(nested(p,["country","data.country","customer.country","user_data.country"])||"Sem país");return {...e,product,payment,country}});const allProducts=[...new Set(enriched.map(e=>e.product))],allSources=[...new Set(enriched.map(e=>e.utmSource||"Direto"))],source=params.get("source"),product=params.get("product"),filtered=enriched.filter(e=>(!source||(e.utmSource||"Direto")===source)&&(!product||e.product===product));const named=(name:string)=>filtered.filter(e=>e.eventName===name),sum=(xs:typeof filtered)=>xs.reduce((s,e)=>s+Number(e.value||0),0),purchases=named("Purchase"),refunds=named("Refund"),chargebacks=named("Chargeback"),pending=named("PaymentPending"),gross=sum(purchases),refundValue=sum(refunds),chargebackValue=sum(chargebacks),net=gross-refundValue-chargebackValue;
 const dailyMap=new Map<string,{date:string,revenue:number,sales:number,pageViews:number;checkouts:number}>(),hourMap=new Map<number,{hour:string,revenue:number,sales:number}>();for(const e of filtered){const d=new Date(e.occurredAt*1000),key=d.toISOString().slice(0,10),dv=dailyMap.get(key)||{date:key,revenue:0,sales:0,pageViews:0,checkouts:0};if(e.eventName==="Purchase"){dv.revenue+=Number(e.value||0);dv.sales++}if(e.eventName==="PageView")dv.pageViews++;if(e.eventName==="InitiateCheckout")dv.checkouts++;dailyMap.set(key,dv);const h=d.getHours(),hv=hourMap.get(h)||{hour:String(h).padStart(2,"0")+"h",revenue:0,sales:0};if(e.eventName==="Purchase"){hv.revenue+=Number(e.value||0);hv.sales++}hourMap.set(h,hv)}
 const group=(field:"product"|"country")=>{const m=new Map<string,{name:string,value:number,sales:number}>();for(const e of purchases){const k=e[field],v=m.get(k)||{name:k,value:0,sales:0};v.value+=Number(e.value||0);v.sales++;m.set(k,v)}return [...m.values()].sort((a,b)=>b.value-a.value)};const sm=new Map<string,{name:string,value:number,sales:number}>();for(const e of purchases){const k=e.utmSource||"Direto",v=sm.get(k)||{name:k,value:0,sales:0};v.value+=Number(e.value||0);v.sales++;sm.set(k,v)}const payments=[["Cartão",/card|cart|credit/],["Pix",/pix/],["Boleto",/boleto/]] as const;const paymentRows=payments.map(([name,re])=>{const approved=purchases.filter(e=>re.test(e.payment)).length,total=approved+pending.filter(e=>re.test(e.payment)).length;return {name,approved,total,rate:total?approved/total*100:null}});
 return Response.json({metrics:{adClicks:named("AdClick").length,pageViews:named("PageView").length,errors:named("PageError").length,viewContent:named("ViewContent").length,checkouts:named("InitiateCheckout").length,sales:purchases.length,pending:pending.length,pendingValue:sum(pending),gross,net,refunds:refunds.length,refundValue,chargebacks:chargebacks.length,chargebackValue,refundRate:purchases.length?refunds.length/purchases.length*100:0},daily:[...dailyMap.values()].sort((a,b)=>a.date.localeCompare(b.date)),hourly:Array.from({length:24},(_,h)=>hourMap.get(h)||{hour:String(h).padStart(2,"0")+"h",revenue:0,sales:0}),products:group("product"),sources:[...sm.values()].sort((a,b)=>b.value-a.value),payments:paymentRows,countries:group("country"),filters:{products:allProducts,sources:allSources},period:r,updatedAt:new Date().toISOString()})}catch(e){console.error("Dashboard GET",e);return Response.json({error:e instanceof Error?e.message:"Falha ao carregar o dashboard."},{status:500})}}
